"""Finance advisory domain — 50 curated seed definitions.

Seeds cover the full spectrum of financial advisory interactions: investment
portfolio review, retirement planning, mortgage/loans, credit disputes,
insurance claims, tax planning, budget advisory, business loans, wealth
management, and fraud/account security.

All data is synthetic. No real PII is present.
"""

from __future__ import annotations

FINANCE_SEEDS: list[dict[str, object]] = [
    # -------------------------------------------------------------------------
    # 1-5: Investment portfolio review
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Asesor de inversiones certificado en banca privada",
            "Cliente": "Inversionista con portafolio diversificado que busca rebalanceo trimestral",
        },
        "objetivo": "Revisión trimestral de portafolio de inversiones con recomendación de rebalanceo",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Saludo y contexto de la revisión trimestral",
                "Resumen de rendimiento del portafolio en el período",
                "Comparación con benchmark de referencia",
                "Análisis de asignación de activos actual vs objetivo",
                "Identificación de desviaciones por asset class",
                "Condiciones de mercado y perspectivas",
                "Propuesta de rebalanceo con justificación",
                "Implicaciones fiscales del rebalanceo propuesto",
                "Confirmación de tolerancia al riesgo vigente",
                "Acuerdo sobre movimientos y ejecución",
            ],
        },
        "parametros_factuales": {
            "contexto": "Banca privada con herramientas de análisis de portafolio y modelos de asignación",
            "restricciones": [
                "Rebalanceo solo si la desviación del objetivo supera la banda del 5%",
                "Considerar impacto fiscal antes de ejecutar ventas",
            ],
            "metadata": {
                "servicio": "banca_privada",
                "tipo_consulta": "revision_trimestral",
                "perfil_riesgo": "moderado",
            },
        },
        "etiquetas": ["inversiones", "portafolio", "rebalanceo", "trimestral", "benchmark"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en fondos de inversión",
            "Cliente": "Inversionista principiante que desea iniciar su primer portafolio",
        },
        "objetivo": "Asesoría para primer inversionista sobre construcción de portafolio inicial diversificado",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Bienvenida y contexto del primer acercamiento",
                "Evaluación de perfil de inversionista: cuestionario de riesgo",
                "Explicación de conceptos básicos: diversificación, horizonte, riesgo-rendimiento",
                "Tipos de instrumentos disponibles: renta fija, variable, fondos",
                "Recomendación de asignación inicial según perfil",
                "Explicación de costos y comisiones",
                "Montos mínimos y estrategia de aportaciones periódicas",
                "Expectativas realistas de rendimiento",
                "Proceso de apertura de cuenta de inversión",
                "Plan de seguimiento y educación financiera continua",
            ],
        },
        "parametros_factuales": {
            "contexto": "Sucursal bancaria con área de asesoría en inversiones y herramienta de perfilamiento",
            "restricciones": [
                "Aplicar cuestionario de perfil de inversión regulatorio antes de recomendar productos",
                "No recomendar productos complejos a inversionistas sin experiencia previa",
            ],
            "metadata": {
                "servicio": "fondos_inversion",
                "tipo_consulta": "primera_vez",
                "perfil_riesgo": "por_determinar",
            },
        },
        "etiquetas": ["inversiones", "principiante", "portafolio_inicial", "perfilamiento", "educacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Analista de inversiones especializadas",
            "Cliente": "Inversionista experimentado evaluando exposición a mercados emergentes",
        },
        "objetivo": "Análisis de oportunidad de inversión en mercados emergentes para portafolio agresivo",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Contexto macroeconómico global actual",
                "Estado actual de la exposición a emergentes en el portafolio",
                "Oportunidades identificadas por región y sector",
                "Riesgos específicos: cambiario, político, liquidez",
                "Vehículos de inversión disponibles: ETFs, fondos activos",
                "Comparativo de costos entre opciones",
                "Tamaño de posición recomendado como porcentaje del portafolio",
                "Estrategia de entrada: gradual vs lump sum",
                "Criterios de salida y stop-loss",
                "Decisión y ejecución",
            ],
        },
        "parametros_factuales": {
            "contexto": "Mesa de operaciones con acceso a investigación de mercados emergentes y ETFs globales",
            "restricciones": [
                "Exposición a mercados emergentes no debe superar 15-20% del portafolio total",
                "Informar sobre riesgo cambiario y opciones de cobertura",
            ],
            "metadata": {
                "servicio": "inversiones_especializadas",
                "tipo_consulta": "oportunidad_inversion",
                "segmento": "mercados_emergentes",
            },
        },
        "etiquetas": ["inversiones", "emergentes", "etf", "riesgo_cambiario", "agresivo"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Gestor de inversiones de renta fija",
            "Cliente": "Inversionista conservador que busca preservación de capital con rendimiento estable",
        },
        "objetivo": "Reestructuración de portafolio de renta fija ante cambio en tasas de interés",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Contexto actual de tasas de interés y perspectivas",
                "Revisión de posiciones actuales de renta fija",
                "Duración promedio del portafolio actual",
                "Impacto de escenarios de tasa en el portafolio",
                "Estrategia propuesta: acortar/alargar duración",
                "Opciones de emisiones disponibles",
                "Rendimiento esperado vs objetivo del cliente",
                "Ejecución de ajustes acordados",
            ],
        },
        "parametros_factuales": {
            "contexto": "Tesorería de banco con acceso a mercado primario y secundario de deuda",
            "restricciones": [
                "Mantener calificación crediticia mínima AA para emisores en portafolio conservador",
                "Laddering de vencimientos para reducir riesgo de reinversión",
            ],
            "metadata": {
                "servicio": "renta_fija",
                "tipo_consulta": "reestructuracion",
                "perfil_riesgo": "conservador",
            },
        },
        "etiquetas": ["inversiones", "renta_fija", "tasas", "duracion", "conservador"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Certified financial planner specializing in ESG investing",
            "Client": "Socially conscious investor seeking to align portfolio with sustainability values",
        },
        "objetivo": "Portfolio restructuring to incorporate ESG criteria without sacrificing risk-adjusted returns",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Understanding client's ESG priorities and values",
                "Current portfolio ESG rating assessment",
                "ESG investment universe and approaches: exclusion, integration, impact",
                "Performance comparison: ESG vs traditional portfolios",
                "Recommended ESG funds and direct investments",
                "Carbon footprint and sustainability metrics",
                "Greenwashing risks and due diligence",
                "Transition plan with cost and tax implications",
                "Reporting and impact measurement framework",
                "Implementation timeline and review schedule",
            ],
        },
        "parametros_factuales": {
            "contexto": "Wealth management firm with ESG research team and sustainable investment products",
            "restricciones": [
                "ESG ratings must come from recognized third-party providers",
                "Disclose any limitations of ESG data and methodologies",
            ],
            "metadata": {
                "servicio": "wealth_management",
                "tipo_consulta": "esg_restructuring",
                "enfoque": "esg_investing",
            },
        },
        "etiquetas": ["investments", "esg", "sustainability", "portfolio", "impact"],
    },
    # -------------------------------------------------------------------------
    # 6-10: Retirement planning consultation
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Planificador financiero para retiro",
            "Cliente": "Profesionista de 45 años que desea proyectar su plan de retiro a los 65",
        },
        "objetivo": "Diseño de plan de retiro personalizado con proyección a 20 años y estrategia de ahorro",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 12,
            "turnos_max": 24,
            "flujo_esperado": [
                "Evaluación de situación financiera actual",
                "Ingresos esperados del sistema de pensiones público",
                "Cálculo de brecha de ingreso en retiro",
                "Estimación de gastos en retiro: básicos, salud, ocio",
                "Ahorro voluntario actual y capacidad de incremento",
                "Opciones de ahorro para el retiro: Afore, PPR, inversiones",
                "Beneficios fiscales de aportaciones voluntarias",
                "Estrategia de inversión por horizonte temporal",
                "Proyección de acumulación con diferentes escenarios",
                "Seguros de vida y gastos médicos mayores",
                "Plan de acción con metas anuales",
                "Revisión anual del plan de retiro",
            ],
        },
        "parametros_factuales": {
            "contexto": "Despacho de planificación financiera con herramientas de proyección actuarial",
            "restricciones": [
                "Proyecciones deben incluir inflación y rendimientos conservadores",
                "Informar sobre tope de deducibilidad fiscal de aportaciones voluntarias",
            ],
            "metadata": {
                "servicio": "planificacion_retiro",
                "tipo_consulta": "diseno_plan",
                "horizonte_anos": "20",
            },
        },
        "etiquetas": ["retiro", "planificacion", "ahorro", "afore", "proyeccion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en pensiones y Afore",
            "Cliente": "Trabajador de 55 años próximo a pensionarse que necesita elegir régimen",
        },
        "objetivo": "Asesoría para elección de régimen de pensión y trámites de retiro anticipado",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Revisión de semanas cotizadas y su validez",
                "Comparación de regímenes de pensión aplicables",
                "Cálculo estimado de pensión bajo cada régimen",
                "Requisitos de edad y semanas para cada opción",
                "Beneficios de modalidad: renta vitalicia vs retiro programado",
                "Impacto de la negativa de pensión y alternativas",
                "Trámites ante instituciones correspondientes",
                "Documentación necesaria para el proceso",
                "Calendario estimado del proceso",
                "Opciones de ahorro complementario post-retiro",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultoría en seguridad social con acceso a simuladores de pensión",
            "restricciones": [
                "Cálculos son estimados y sujetos a validación por la institución de seguridad social",
                "Diferenciar claramente entre régimen de 1973 y 1997 según ley aplicable",
            ],
            "metadata": {
                "servicio": "pensiones",
                "tipo_consulta": "pre_retiro",
                "edad_cliente": "55",
            },
        },
        "etiquetas": ["retiro", "pension", "afore", "regimen", "tramites"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Planificador financiero de retiro anticipado",
            "Cliente": "Emprendedor de 40 años que desea lograr independencia financiera anticipada",
        },
        "objetivo": "Estrategia de independencia financiera anticipada con portafolio de ingresos pasivos",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Definición de metas y estilo de vida deseado en retiro anticipado",
                "Evaluación de patrimonio neto actual",
                "Cálculo del número mágico: 25x gastos anuales",
                "Fuentes actuales y potenciales de ingreso pasivo",
                "Estrategia de inversión para generación de cash flow",
                "Bienes raíces vs instrumentos financieros vs negocio",
                "Optimización fiscal de ingresos pasivos",
                "Plan de transición gradual del empleo activo",
                "Cobertura de salud y seguros post-retiro anticipado",
                "Prueba de estrés del plan ante diferentes escenarios",
            ],
        },
        "parametros_factuales": {
            "contexto": (
                "Consultoría financiera independiente especializada en FIRE (Financial Independence, Retire Early)"
            ),
            "restricciones": [
                "Tasa de retiro seguro del 3.5-4% del portafolio acumulado",
                "Incluir cobertura de gastos médicos que no cubre el sistema público antes de edad de pensión",
            ],
            "metadata": {
                "servicio": "independencia_financiera",
                "tipo_consulta": "retiro_anticipado",
                "estrategia": "fire",
            },
        },
        "etiquetas": ["retiro", "fire", "independencia_financiera", "ingreso_pasivo", "anticipado"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Consultor de beneficios corporativos de retiro",
            "Cliente": "Director de recursos humanos que evalúa plan de pensiones complementario para empleados",
        },
        "objetivo": "Diseño de plan de pensiones complementario corporativo como beneficio para empleados",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Objetivos de la empresa con el plan de retiro complementario",
                "Población elegible y demografía de empleados",
                "Tipos de planes disponibles: contribución definida vs beneficio definido",
                "Estructura de aportaciones: empresa, empleado, matching",
                "Vehículos de inversión para el fondo",
                "Reglas de vestimiento y permanencia",
                "Beneficios fiscales para la empresa y empleados",
                "Administración y gobernanza del plan",
                "Comunicación y educación a empleados",
                "Implementación y cronograma",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultoría de beneficios con experiencia en planes de pensiones corporativos regulados",
            "restricciones": [
                "Plan debe cumplir con normativa de la comisión reguladora correspondiente",
                "Aportaciones patronales son deducibles de impuestos hasta el tope legal",
            ],
            "metadata": {
                "servicio": "planes_corporativos",
                "tipo_consulta": "diseno_plan_pensiones",
                "tipo_cliente": "corporativo",
            },
        },
        "etiquetas": ["retiro", "corporativo", "plan_pensiones", "beneficios", "rrhh"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Retirement income specialist",
            "Client": "Recently retired individual seeking to convert savings into sustainable income stream",
        },
        "objetivo": "Retirement income distribution strategy to ensure savings last through a 30-year retirement",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Total retirement asset inventory",
                "Fixed income sources: social security, pensions",
                "Monthly expense estimation and categorization",
                "Income gap analysis",
                "Withdrawal strategy: bucket approach or systematic",
                "Tax-efficient withdrawal sequencing",
                "Annuity vs systematic withdrawal comparison",
                "Healthcare cost planning including long-term care",
                "Inflation protection strategies",
                "Estate planning integration and beneficiary review",
            ],
        },
        "parametros_factuales": {
            "contexto": "Retirement planning firm with Monte Carlo simulation and income projection tools",
            "restricciones": [
                "Safe withdrawal rate of 3.5-4% adjusted for portfolio composition and longevity risk",
                "Required minimum distributions must be factored starting at applicable age",
            ],
            "metadata": {
                "servicio": "retirement_income",
                "tipo_consulta": "distribution_strategy",
                "fase": "post_retirement",
            },
        },
        "etiquetas": ["retirement", "income", "distribution", "withdrawal", "longevity"],
    },
    # -------------------------------------------------------------------------
    # 11-15: Mortgage / loan application
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de crédito hipotecario bancario",
            "Cliente": "Pareja joven que solicita su primer crédito hipotecario",
        },
        "objetivo": "Asesoría integral para primer crédito hipotecario incluyendo precalificación y opciones",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 12,
            "turnos_max": 24,
            "flujo_esperado": [
                "Bienvenida y exploración de necesidades de vivienda",
                "Evaluación de capacidad de pago: ingresos vs deudas",
                "Precalificación según perfil crediticio",
                "Monto máximo de crédito pre-autorizado",
                "Tipos de crédito disponibles: tasa fija, variable, mixta",
                "Plazos disponibles y comparativo de mensualidades",
                "Gastos adicionales: notariales, avalúo, seguros",
                "Enganche requerido y opciones de apoyo gubernamental",
                "Simulación de pagos con diferentes escenarios",
                "Documentación requerida para formalizar solicitud",
                "Proceso y tiempos desde solicitud hasta escrituración",
                "Compromiso de acompañamiento durante todo el proceso",
            ],
        },
        "parametros_factuales": {
            "contexto": "Sucursal bancaria con herramientas de simulación hipotecaria y convenios con desarrolladores",
            "restricciones": [
                "Capacidad de pago no debe superar 30% del ingreso neto familiar",
                "Precalificación no garantiza aprobación final del crédito",
            ],
            "metadata": {
                "servicio": "credito_hipotecario",
                "tipo_consulta": "primera_solicitud",
                "tipo_credito": "hipotecario",
            },
        },
        "etiquetas": ["hipotecario", "primer_credito", "precalificacion", "vivienda", "simulacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en refinanciamiento hipotecario",
            "Cliente": "Propietario que busca mejorar condiciones de su hipoteca actual",
        },
        "objetivo": "Análisis de conveniencia de refinanciamiento hipotecario por baja en tasas de interés",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Revisión de condiciones del crédito hipotecario actual",
                "Saldo insoluto y plazo remanente",
                "Nuevas condiciones disponibles en el mercado",
                "Cálculo de ahorro potencial mensual y total",
                "Costos del refinanciamiento: comisiones, avalúo, notarial",
                "Punto de equilibrio: cuándo el ahorro supera los costos",
                "Proceso y requisitos del refinanciamiento",
                "Decisión y siguientes pasos",
            ],
        },
        "parametros_factuales": {
            "contexto": "Área de crédito hipotecario con comparador de opciones de refinanciamiento",
            "restricciones": [
                "Refinanciamiento solo conviene si la diferencia de tasa supera 1-2 puntos porcentuales",
                "Verificar que no haya penalización por prepago en el crédito actual",
            ],
            "metadata": {
                "servicio": "refinanciamiento",
                "tipo_consulta": "analisis_conveniencia",
                "tipo_credito": "hipotecario",
            },
        },
        "etiquetas": ["hipotecario", "refinanciamiento", "tasas", "ahorro", "analisis"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de créditos personales y de nómina",
            "Cliente": "Empleado que necesita un préstamo personal para consolidar deudas de tarjetas",
        },
        "objetivo": "Asesoría sobre préstamo personal para consolidación de deudas de tarjetas de crédito",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Diagnóstico de deudas actuales: montos, tasas, mínimos",
                "Evaluación de la conveniencia de consolidación",
                "Comparación de tasa del préstamo personal vs tarjetas",
                "Cálculo de ahorro en intereses y plazo de pago",
                "Opciones de préstamo personal y de nómina disponibles",
                "CAT comparativo entre opciones",
                "Plan de pago y compromiso de no generar nueva deuda",
                "Documentación y proceso de solicitud",
            ],
        },
        "parametros_factuales": {
            "contexto": "Sucursal bancaria con herramienta de consolidación de deudas y simuladores",
            "restricciones": [
                "Consolidación solo es conveniente si la tasa del nuevo crédito es menor a la ponderada de deudas",
                "Incluir CAT (Costo Anual Total) en toda comparación",
            ],
            "metadata": {
                "servicio": "credito_personal",
                "tipo_consulta": "consolidacion_deudas",
                "producto": "prestamo_personal",
            },
        },
        "etiquetas": ["credito", "personal", "consolidacion", "deudas", "tarjetas"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en crédito automotriz del banco",
            "Cliente": "Persona que solicita crédito para compra de auto nuevo",
        },
        "objetivo": "Evaluación y aprobación de crédito automotriz bancario para vehículo nuevo",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Identificación del vehículo y monto requerido",
                "Evaluación de capacidad de pago e historial crediticio",
                "Presentación de opciones de plazo y tasa",
                "Cálculo de mensualidad y CAT para cada opción",
                "Requisito de enganche y seguro",
                "Comisión por apertura y gastos de gestoría",
                "Documentación necesaria para la solicitud",
                "Proceso de aprobación y desembolso",
            ],
        },
        "parametros_factuales": {
            "contexto": "Área de crédito automotriz bancario con convenios con concesionarias",
            "restricciones": [
                "Enganche mínimo del 10-20% según política del banco",
                "Seguro de cobertura amplia obligatorio durante la vigencia del crédito",
            ],
            "metadata": {
                "servicio": "credito_automotriz",
                "tipo_consulta": "solicitud",
                "tipo_credito": "automotriz",
            },
        },
        "etiquetas": ["credito", "automotriz", "banco", "aprobacion", "mensualidad"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Mortgage loan officer at a community bank",
            "Client": "Self-employed individual applying for a home loan with non-traditional income documentation",
        },
        "objetivo": (
            "Mortgage qualification guidance for self-employed borrower with bank statement income verification"
        ),
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Introduction and self-employment income overview",
                "Bank statement program explanation vs traditional documentation",
                "12 vs 24 month bank statement options",
                "Income calculation methodology for self-employed",
                "Down payment requirements and reserves",
                "Interest rate comparison: bank statement vs conventional",
                "Pre-approval process and documentation checklist",
                "Property type and loan limit considerations",
                "Timeline from pre-approval to closing",
                "Next steps and document submission",
            ],
        },
        "parametros_factuales": {
            "contexto": "Community bank with non-QM lending programs for self-employed borrowers",
            "restricciones": [
                "Bank statement loans typically require 10-20% minimum down payment",
                "Two years of self-employment history generally required",
            ],
            "metadata": {
                "servicio": "mortgage",
                "tipo_consulta": "qualification",
                "programa": "bank_statement",
                "borrower_type": "self_employed",
            },
        },
        "etiquetas": ["mortgage", "self_employed", "bank_statement", "non_qm", "home_loan"],
    },
    # -------------------------------------------------------------------------
    # 16-20: Credit card dispute
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de aclaraciones de tarjeta de crédito",
            "Cliente": "Tarjetahabiente que detectó cargo no reconocido en su estado de cuenta",
        },
        "objetivo": "Proceso de aclaración por cargo no reconocido en tarjeta de crédito",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Identificación del tarjetahabiente y verificación de seguridad",
                "Detalle del cargo en disputa: monto, fecha, comercio",
                "Verificación de si es cargo recurrente o suscripción",
                "Registro formal de la aclaración",
                "Bloqueo preventivo de la tarjeta si hay sospecha de fraude",
                "Emisión de tarjeta de reemplazo si necesario",
                "Plazo legal para resolución de la aclaración",
                "Crédito provisional mientras se investiga",
            ],
        },
        "parametros_factuales": {
            "contexto": "Centro de aclaraciones bancarias con acceso a sistema de disputas y monitoreo de fraude",
            "restricciones": [
                "Plazo máximo de resolución según normativa del regulador bancario",
                "Crédito provisional debe aplicarse según regulación aplicable",
            ],
            "metadata": {
                "servicio": "tarjeta_credito",
                "tipo_consulta": "aclaracion",
                "motivo": "cargo_no_reconocido",
            },
        },
        "etiquetas": ["tarjeta", "aclaracion", "cargo_no_reconocido", "disputa", "fraude"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en reclamaciones de consumo bancario",
            "Cliente": "Tarjetahabiente que pagó por producto que nunca recibió en compra en línea",
        },
        "objetivo": "Disputa de cargo por producto no recibido en compra realizada con tarjeta de crédito en línea",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Verificación de identidad del tarjetahabiente",
                "Detalle de la transacción en disputa",
                "Evidencia de la compra: confirmación, número de pedido",
                "Intentos previos de resolución con el comercio",
                "Registro de la disputa formal ante el banco",
                "Proceso de chargeback y tiempos",
                "Documentación de soporte requerida",
                "Seguimiento del caso y resolución esperada",
            ],
        },
        "parametros_factuales": {
            "contexto": "Unidad de disputas bancarias con proceso de chargeback a través de redes de pago",
            "restricciones": [
                "El tarjetahabiente debe demostrar que intentó resolver con el comercio primero",
                "Disputa debe iniciarse dentro del plazo establecido por la red de pago",
            ],
            "metadata": {
                "servicio": "tarjeta_credito",
                "tipo_consulta": "disputa",
                "motivo": "producto_no_recibido",
                "canal": "compra_en_linea",
            },
        },
        "etiquetas": ["tarjeta", "disputa", "chargeback", "comercio_electronico", "no_recibido"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de atención al cliente de tarjetas",
            "Cliente": "Tarjetahabiente que recibió cobro duplicado por la misma transacción",
        },
        "objetivo": "Resolución de cobro duplicado en tarjeta de crédito por error de procesamiento",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 6,
            "turnos_max": 14,
            "flujo_esperado": [
                "Verificación de identidad y cuenta",
                "Identificación de las transacciones duplicadas",
                "Confirmación en sistema de que es cobro duplicado",
                "Solicitud de reverso inmediato si es error evidente",
                "Explicación del plazo para ver reflejado el crédito",
                "Confirmación por escrito de la resolución",
            ],
        },
        "parametros_factuales": {
            "contexto": "Centro de atención con acceso a sistema de transacciones en tiempo real",
            "restricciones": [
                "Duplicados evidentes pueden reversarse en el momento sin proceso formal de disputa",
                "El crédito debe reflejarse en el siguiente corte o antes",
            ],
            "metadata": {
                "servicio": "tarjeta_credito",
                "tipo_consulta": "aclaracion",
                "motivo": "cobro_duplicado",
            },
        },
        "etiquetas": ["tarjeta", "duplicado", "reverso", "error", "procesamiento"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en promociones y beneficios de tarjeta",
            "Cliente": "Tarjetahabiente que no recibió los puntos de programa de recompensas prometidos",
        },
        "objetivo": "Reclamación de puntos de recompensa no acreditados por promoción de tarjeta de crédito",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 6,
            "turnos_max": 14,
            "flujo_esperado": [
                "Verificación de la cuenta y programa de recompensas",
                "Identificación de la promoción en cuestión",
                "Verificación de cumplimiento de términos y condiciones",
                "Revisión de transacciones elegibles",
                "Acreditación manual de puntos si aplica",
                "Confirmación y plazo para ver puntos reflejados",
            ],
        },
        "parametros_factuales": {
            "contexto": "Centro de servicio con acceso a plataforma de programa de recompensas",
            "restricciones": [
                "Verificar que las transacciones cumplan los términos de la promoción",
                "Acreditación manual requiere validación de supervisor",
            ],
            "metadata": {
                "servicio": "tarjeta_credito",
                "tipo_consulta": "reclamacion_puntos",
                "programa": "recompensas",
            },
        },
        "etiquetas": ["tarjeta", "puntos", "recompensas", "promocion", "reclamacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Fraud investigation specialist at credit card company",
            "Client": "Cardholder who discovered multiple unauthorized international charges",
        },
        "objetivo": "Investigation and resolution of multiple unauthorized international charges on credit card",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Identity verification with enhanced security questions",
                "Detailed review of all disputed transactions",
                "Confirmation that cardholder was not traveling internationally",
                "Immediate card freeze and fraud alert placement",
                "Provisional credit issuance for all disputed amounts",
                "New card issuance with expedited shipping",
                "Fraud investigation timeline and process explanation",
                "Identity theft protection resources and monitoring",
            ],
        },
        "parametros_factuales": {
            "contexto": "Credit card fraud department with real-time transaction monitoring and investigation tools",
            "restricciones": [
                "Provisional credits must be issued per regulatory requirements",
                "Card must be blocked immediately upon confirmed unauthorized activity",
            ],
            "metadata": {
                "servicio": "credit_card",
                "tipo_consulta": "fraud_investigation",
                "motivo": "unauthorized_international_charges",
            },
        },
        "etiquetas": ["credit_card", "fraud", "unauthorized", "international", "investigation"],
    },
    # -------------------------------------------------------------------------
    # 21-25: Insurance claim
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ajustador de siniestros de seguro de hogar",
            "Cliente": "Asegurado que sufrió daños por inundación en su vivienda",
        },
        "objetivo": "Proceso de reclamación de seguro de hogar por daños por inundación",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Reporte inicial del siniestro: fecha, circunstancias",
                "Verificación de cobertura de daños por fenómenos naturales",
                "Documentación fotográfica y video del daño",
                "Inventario de bienes afectados",
                "Asignación de ajustador y fecha de visita",
                "Proceso de evaluación y dictamen del daño",
                "Estimación de monto de indemnización",
                "Deducible aplicable y forma de pago",
                "Proveedores autorizados para reparación",
                "Seguimiento del proceso hasta resolución completa",
            ],
        },
        "parametros_factuales": {
            "contexto": "Compañía aseguradora con red de ajustadores y proveedores de reparación autorizados",
            "restricciones": [
                "Siniestro debe reportarse dentro de las primeras 48 horas",
                "No iniciar reparaciones antes de la visita del ajustador excepto medidas de emergencia",
            ],
            "metadata": {
                "servicio": "seguros",
                "tipo_seguro": "hogar",
                "tipo_siniestro": "inundacion",
            },
        },
        "etiquetas": ["seguro", "hogar", "siniestro", "inundacion", "reclamacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Gestor de siniestros de seguro de vida",
            "Cliente": "Beneficiario que presenta reclamación por fallecimiento del titular",
        },
        "objetivo": "Acompañamiento en proceso de reclamación de seguro de vida por fallecimiento",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Recepción empática y expresión de condolencias",
                "Verificación de la póliza y beneficiarios designados",
                "Documentación requerida: acta de defunción, identificaciones",
                "Explicación del proceso de reclamación",
                "Suma asegurada y beneficios adicionales",
                "Plazos legales para el pago",
                "Opciones de pago: lump sum o renta",
                "Asesoría sobre implicaciones fiscales del beneficio",
            ],
        },
        "parametros_factuales": {
            "contexto": "Departamento de siniestros de vida con protocolo de atención sensible",
            "restricciones": [
                "Atención con enfoque empático y sensible a la situación del beneficiario",
                "Plazo legal máximo para el pago según legislación de seguros vigente",
            ],
            "metadata": {
                "servicio": "seguros",
                "tipo_seguro": "vida",
                "tipo_siniestro": "fallecimiento",
            },
        },
        "etiquetas": ["seguro", "vida", "fallecimiento", "beneficiario", "reclamacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en reclamaciones de gastos médicos mayores",
            "Cliente": "Asegurado que requiere autorización para procedimiento quirúrgico electivo",
        },
        "objetivo": "Proceso de autorización previa para cirugía electiva cubierta por póliza de gastos médicos",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Verificación de póliza y vigencia de cobertura",
                "Revisión del diagnóstico y procedimiento propuesto",
                "Verificación de preexistencias y períodos de espera",
                "Revisión de red médica: hospital y cirujano",
                "Cálculo de costos cubiertos y deducible/coaseguro",
                "Documentación médica requerida para autorización",
                "Plazo de respuesta para la autorización",
                "Proceso de reembolso si se elige red abierta",
            ],
        },
        "parametros_factuales": {
            "contexto": "Área de autorizaciones médicas con equipo de revisión clínica y administrativa",
            "restricciones": [
                "Autorización previa obligatoria para procedimientos electivos con costo mayor al tope definido",
                "Procedimiento debe tener indicación médica documentada",
            ],
            "metadata": {
                "servicio": "seguros",
                "tipo_seguro": "gastos_medicos_mayores",
                "tipo_tramite": "autorizacion_previa",
            },
        },
        "etiquetas": ["seguro", "gastos_medicos", "autorizacion", "cirugia", "cobertura"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ajustador de reclamaciones de seguro empresarial",
            "Cliente": "Dueño de negocio que sufrió robo con violencia en su local comercial",
        },
        "objetivo": "Reclamación de seguro empresarial por robo con violencia en establecimiento comercial",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Reporte del siniestro y verificación de denuncia ante autoridades",
                "Verificación de cobertura de robo con violencia en la póliza",
                "Documentación del inventario de bienes sustraídos",
                "Evidencia: videos de seguridad, reportes policiales",
                "Evaluación de daños a la propiedad durante el robo",
                "Asignación de ajustador e investigador de siniestros",
                "Proceso de verificación y dictamen",
                "Estimación de indemnización: bienes y daños",
                "Interrupción de negocio: pérdida consecuencial",
                "Plan de rehabilitación y mejora de seguridad",
            ],
        },
        "parametros_factuales": {
            "contexto": "Compañía aseguradora con división de siniestros empresariales y equipo de investigación",
            "restricciones": [
                "Denuncia ante ministerio público es requisito indispensable para procedencia",
                "Inventario de bienes robados debe coincidir con declaración previa de la póliza",
            ],
            "metadata": {
                "servicio": "seguros",
                "tipo_seguro": "empresarial",
                "tipo_siniestro": "robo_con_violencia",
            },
        },
        "etiquetas": ["seguro", "empresarial", "robo", "reclamacion", "inventario"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Insurance claims adjuster for business interruption",
            "Client": "Business owner filing claim for revenue loss due to covered property damage",
        },
        "objetivo": "Business interruption insurance claim process for revenue loss during covered restoration period",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Initial claim filing and event documentation",
                "Policy coverage verification for business interruption",
                "Waiting period and coverage period explanation",
                "Revenue loss calculation methodology",
                "Required financial documentation: P&L, tax returns, projections",
                "Continuing expenses vs saved expenses",
                "Extra expense coverage for mitigation efforts",
                "Forensic accountant assignment if needed",
                "Advance payment possibility for immediate needs",
                "Claim settlement timeline and dispute resolution",
            ],
        },
        "parametros_factuales": {
            "contexto": "Commercial insurance company with specialized business interruption claims unit",
            "restricciones": [
                "Business interruption coverage is tied to the property damage claim",
                "Revenue loss must be documented with pre-loss financial records",
            ],
            "metadata": {
                "servicio": "insurance",
                "tipo_seguro": "commercial",
                "tipo_siniestro": "business_interruption",
            },
        },
        "etiquetas": ["insurance", "business_interruption", "claim", "revenue_loss", "commercial"],
    },
    # -------------------------------------------------------------------------
    # 26-30: Tax planning discussion
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Contador público especializado en impuestos personales",
            "Cliente": "Asalariado que desea optimizar su declaración anual de impuestos",
        },
        "objetivo": "Planificación fiscal para optimizar deducciones personales en declaración anual",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Revisión de ingresos del ejercicio fiscal",
                "Identificación de deducciones personales aplicables",
                "Gastos médicos, dentales y hospitalarios deducibles",
                "Intereses hipotecarios y colegiaturas",
                "Aportaciones voluntarias al retiro deducibles",
                "Donativos y seguros deducibles",
                "Cálculo de saldo a favor estimado",
                "Estrategia de facturación y comprobantes para siguiente año",
            ],
        },
        "parametros_factuales": {
            "contexto": "Despacho contable con acceso a plataforma tributaria y expedientes fiscales",
            "restricciones": [
                "Tope de deducciones personales según legislación fiscal vigente",
                "Todos los gastos deducibles requieren factura electrónica válida",
            ],
            "metadata": {
                "servicio": "fiscal",
                "tipo_consulta": "planificacion",
                "tipo_contribuyente": "persona_fisica_asalariado",
            },
        },
        "etiquetas": ["fiscal", "deducciones", "declaracion_anual", "persona_fisica", "optimizacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Asesor fiscal empresarial",
            "Cliente": "Dueño de pequeña empresa que necesita planificar obligaciones fiscales del siguiente año",
        },
        "objetivo": "Planificación fiscal anual para pequeña empresa con optimización de régimen tributario",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Revisión de régimen fiscal actual de la empresa",
                "Proyección de ingresos y gastos del siguiente ejercicio",
                "Evaluación de conveniencia de cambio de régimen",
                "Estrategia de deducción de inversiones y activos",
                "Planeación de pagos provisionales",
                "Beneficios fiscales y estímulos aplicables",
                "Obligaciones de retención y entero de impuestos",
                "Calendario fiscal con fechas clave",
                "Riesgos fiscales y cómo mitigarlos",
                "Plan de acción mensual y trimestral",
            ],
        },
        "parametros_factuales": {
            "contexto": "Despacho contable-fiscal especializado en PyMEs con sistema de contabilidad integrado",
            "restricciones": [
                "Verificar topes de ingresos para regímenes simplificados",
                "Toda planeación debe estar dentro del marco legal, nunca evasión",
            ],
            "metadata": {
                "servicio": "fiscal",
                "tipo_consulta": "planificacion_anual",
                "tipo_contribuyente": "persona_moral_pyme",
            },
        },
        "etiquetas": ["fiscal", "pyme", "planificacion", "regimen", "obligaciones"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en impuestos de bienes raíces",
            "Cliente": "Propietario que va a vender un inmueble y necesita entender las implicaciones fiscales",
        },
        "objetivo": "Asesoría sobre implicaciones fiscales de la venta de inmueble y estrategias de diferimiento",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Detalles del inmueble: fecha de adquisición, costo, mejoras",
                "Cálculo de ganancia patrimonial actualizada",
                "Impuesto sobre la renta por enajenación de inmuebles",
                "Exenciones aplicables: vivienda habitual, monto exento",
                "Estrategias de diferimiento fiscal",
                "Retención que realizará el notario",
                "Impuestos locales: ISAI, predial a regularizar",
                "Recomendaciones para la operación de venta",
            ],
        },
        "parametros_factuales": {
            "contexto": "Despacho fiscal con experiencia en operaciones inmobiliarias y cálculos de ISR",
            "restricciones": [
                "Exención por venta de casa habitación aplica una vez cada 3-5 años según legislación",
                "Ganancia se calcula sobre costo actualizado por inflación desde la adquisición",
            ],
            "metadata": {
                "servicio": "fiscal",
                "tipo_consulta": "asesoria",
                "tema": "venta_inmueble",
            },
        },
        "etiquetas": ["fiscal", "inmobiliario", "venta", "isr", "ganancia_patrimonial"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Consultor fiscal internacional",
            "Cliente": "Profesionista con ingresos en el extranjero que necesita regularizar su situación fiscal",
        },
        "objetivo": (
            "Regularización fiscal de ingresos del extranjero y acreditamiento de impuestos pagados en otro país"
        ),
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Determinación de residencia fiscal",
                "Fuentes de ingreso en el extranjero: tipo y país",
                "Convenios de doble tributación aplicables",
                "Obligaciones de declaración de ingresos mundiales",
                "Cálculo de impuesto con acreditamiento del impuesto extranjero",
                "Cuentas y activos financieros en el exterior: obligaciones informativas",
                "Regularización de ejercicios anteriores si aplica",
                "Declaraciones informativas obligatorias",
                "Plan de cumplimiento fiscal internacional",
                "Documentación necesaria para soporte",
            ],
        },
        "parametros_factuales": {
            "contexto": "Firma fiscal con práctica de fiscalidad internacional y tratados tributarios",
            "restricciones": [
                "Residentes fiscales deben declarar ingresos mundiales",
                "Acreditamiento de impuestos extranjeros limitado al impuesto local correspondiente",
            ],
            "metadata": {
                "servicio": "fiscal_internacional",
                "tipo_consulta": "regularizacion",
                "tema": "ingresos_extranjero",
            },
        },
        "etiquetas": ["fiscal", "internacional", "doble_tributacion", "regularizacion", "residencia"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Tax planning specialist for high-net-worth individuals",
            "Client": "Executive with stock options and RSUs seeking tax-efficient exercise strategy",
        },
        "objetivo": "Tax-efficient strategy for exercising stock options and managing RSU vesting events",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Inventory of stock compensation: ISOs, NQSOs, RSUs",
                "Vesting schedule and expiration dates",
                "Current stock price vs exercise price analysis",
                "Tax implications of each type: ordinary income vs capital gains",
                "AMT considerations for ISOs",
                "Exercise and hold vs exercise and sell strategies",
                "Concentration risk and diversification needs",
                "Tax loss harvesting opportunities",
                "Estimated tax payment planning",
                "Multi-year exercise strategy to manage tax brackets",
            ],
        },
        "parametros_factuales": {
            "contexto": "Tax advisory firm specializing in executive compensation and equity-based pay",
            "restricciones": [
                "ISO exercise may trigger AMT liability that must be modeled",
                "Rule 10b5-1 trading plans may be needed for insider trading compliance",
            ],
            "metadata": {
                "servicio": "tax_planning",
                "tipo_consulta": "equity_compensation",
                "instruments": "iso_nqso_rsu",
            },
        },
        "etiquetas": ["tax", "stock_options", "rsu", "equity_compensation", "amt"],
    },
    # -------------------------------------------------------------------------
    # 31-35: Budget advisory
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Educador financiero en programa de bienestar",
            "Cliente": "Joven profesional que quiere establecer su primer presupuesto mensual",
        },
        "objetivo": "Creación de primer presupuesto personal mensual con método 50/30/20 adaptado",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Ingreso neto mensual y estabilidad del ingreso",
                "Gastos fijos mensuales: renta, servicios, transporte",
                "Gastos variables: alimentación, entretenimiento, vestimenta",
                "Identificación de fugas de dinero y gastos hormiga",
                "Introducción al método 50/30/20",
                "Adaptación del método a su realidad",
                "Meta de fondo de emergencia: 3-6 meses de gastos",
                "Herramientas de seguimiento: app o planilla",
            ],
        },
        "parametros_factuales": {
            "contexto": "Programa de educación financiera con herramientas digitales de presupuesto",
            "restricciones": [
                "Presupuesto debe ser realista y flexible, no restrictivo",
                "Priorizar fondo de emergencia antes que inversiones",
            ],
            "metadata": {
                "servicio": "educacion_financiera",
                "tipo_consulta": "presupuesto",
                "metodo": "50_30_20",
            },
        },
        "etiquetas": ["presupuesto", "educacion_financiera", "primer_presupuesto", "50_30_20"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Coach financiero personal",
            "Cliente": "Familia con dos ingresos que quiere salir de deudas y empezar a ahorrar",
        },
        "objetivo": "Plan de eliminación de deudas para familia con método bola de nieve y presupuesto familiar",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Inventario completo de deudas: monto, tasa, mínimo mensual",
                "Ingresos familiares combinados y gastos del hogar",
                "Identificación de gastos recortables",
                "Explicación del método bola de nieve vs avalancha",
                "Selección del método según perfil de la familia",
                "Cálculo de pago extra mensual disponible para deudas",
                "Línea de tiempo estimada para quedar libre de deudas",
                "Estrategia para evitar nueva deuda durante el proceso",
                "Metas de ahorro post-deuda",
                "Sesiones de seguimiento y rendición de cuentas",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de coaching financiero con herramientas de simulación de deuda",
            "restricciones": [
                "Método bola de nieve: pagar la deuda más pequeña primero para motivación",
                "Método avalancha: pagar la de mayor tasa primero para ahorro en intereses",
            ],
            "metadata": {
                "servicio": "coaching_financiero",
                "tipo_consulta": "eliminacion_deudas",
                "metodo": "bola_de_nieve",
            },
        },
        "etiquetas": ["presupuesto", "deudas", "bola_de_nieve", "familia", "ahorro"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Planificador financiero de eventos de vida",
            "Cliente": "Pareja que planifica financieramente la llegada de su primer hijo",
        },
        "objetivo": "Planificación financiera para la llegada del primer bebé: gastos, ahorro, y seguros",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Situación financiera actual de la pareja",
                "Estimación de gastos del embarazo y parto",
                "Gastos recurrentes del primer año: pañales, alimentación, pediatra",
                "Impacto en ingreso si uno de los padres reduce jornada",
                "Ajuste de presupuesto familiar con nueva realidad",
                "Seguro de gastos médicos: cobertura de maternidad",
                "Seguro de vida y beneficiarios",
                "Inicio de ahorro educativo a largo plazo",
                "Fondo de emergencia familiar ampliado",
                "Beneficios laborales: licencia de maternidad/paternidad",
            ],
        },
        "parametros_factuales": {
            "contexto": "Despacho de planificación financiera familiar con especializacion en eventos de vida",
            "restricciones": [
                "Incluir período de espera de seguros si se contrata nuevo",
                "Seguro de vida recomendado con cobertura de al menos 10 veces el ingreso anual",
            ],
            "metadata": {
                "servicio": "planificacion_familiar",
                "tipo_consulta": "evento_de_vida",
                "evento": "primer_hijo",
            },
        },
        "etiquetas": ["presupuesto", "familia", "bebe", "planificacion", "seguro_vida"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Asesor de finanzas personales post-divorcio",
            "Cliente": "Persona recientemente divorciada que necesita reorganizar sus finanzas individuales",
        },
        "objetivo": "Reorganización financiera post-divorcio con nuevo presupuesto individual y ajuste patrimonial",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Inventario de patrimonio post-división de bienes",
                "Nuevo ingreso individual y obligaciones",
                "Pensiones alimenticias: dadas o recibidas",
                "Nuevo presupuesto mensual individual",
                "Revisión de deudas compartidas y su asignación",
                "Actualización de beneficiarios en seguros y cuentas",
                "Reevaluación de necesidades de seguros",
                "Plan de ahorro y reconstrucción patrimonial",
                "Testamento y voluntad anticipada: actualización",
                "Apoyo emocional y recursos adicionales",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultora de finanzas personales con sensibilidad para transiciones de vida",
            "restricciones": [
                "Verificar que la división de bienes del convenio se refleje en cuentas e hipotecas",
                "Actualizar beneficiarios es urgente para evitar complicaciones legales",
            ],
            "metadata": {
                "servicio": "planificacion_personal",
                "tipo_consulta": "reorganizacion",
                "evento": "divorcio",
            },
        },
        "etiquetas": ["presupuesto", "divorcio", "reorganizacion", "patrimonio", "beneficiarios"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Financial wellness counselor at employee assistance program",
            "Client": "Employee seeking help managing finances after unexpected job loss of spouse",
        },
        "objetivo": "Emergency financial plan for household facing sudden income reduction due to spouse job loss",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Current financial situation assessment: income, expenses, savings",
                "Immediate expense triage: needs vs wants",
                "Emergency fund status and drawdown plan",
                "Unemployment benefits and eligibility",
                "Health insurance continuation options (COBRA equivalent)",
                "Creditor communication and hardship programs",
                "Temporary budget with reduced income",
                "Job transition timeline and financial bridge strategy",
            ],
        },
        "parametros_factuales": {
            "contexto": "Employee assistance program with financial counseling services",
            "restricciones": [
                "Focus on immediate stabilization before long-term planning",
                "Refer to legal aid if debt situation becomes critical",
            ],
            "metadata": {
                "servicio": "financial_wellness",
                "tipo_consulta": "emergency_plan",
                "evento": "job_loss",
            },
        },
        "etiquetas": ["budget", "emergency", "job_loss", "income_reduction", "financial_wellness"],
    },
    # -------------------------------------------------------------------------
    # 36-40: Business loan consultation
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de crédito empresarial PyME",
            "Cliente": "Dueño de restaurante que necesita capital de trabajo para temporada alta",
        },
        "objetivo": "Solicitud de línea de crédito revolvente para capital de trabajo de restaurante",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Perfil del negocio: antigüedad, ventas, empleados",
                "Necesidad específica de capital de trabajo",
                "Revisión de estados financieros y flujo de caja",
                "Historial crediticio del negocio y representante legal",
                "Opciones de producto: línea revolvente, factoraje, crédito simple",
                "Condiciones: tasa, plazo, comisiones, garantías",
                "Documentación requerida para la solicitud",
                "Proceso de evaluación y tiempos de respuesta",
            ],
        },
        "parametros_factuales": {
            "contexto": "Banco comercial con programas de crédito PyME y garantías gubernamentales",
            "restricciones": [
                "Negocio debe tener mínimo 2 años de operación para crédito sin garantía gubernamental",
                "Capacidad de pago se evalúa sobre flujo de caja, no solo ventas",
            ],
            "metadata": {
                "servicio": "credito_empresarial",
                "tipo_credito": "capital_trabajo",
                "segmento": "pyme_restaurante",
            },
        },
        "etiquetas": ["credito", "empresarial", "pyme", "capital_trabajo", "restaurante"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de banca de inversión para startups",
            "Cliente": "Fundador de startup tecnológica que busca financiamiento para crecimiento",
        },
        "objetivo": "Evaluación de opciones de financiamiento para startup en etapa de crecimiento: deuda vs equity",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Estado actual de la startup: métricas, tracción, equipo",
                "Monto de capital requerido y uso de fondos",
                "Opciones de financiamiento: capital de riesgo, deuda, subvenciones",
                "Pros y contras de levantar equity vs tomar deuda",
                "Valuación actual y dilución esperada",
                "Venture debt como complemento a ronda de equity",
                "Programas de aceleración y fondos gubernamentales",
                "Estructura de terms sheet básica",
                "Preparación para due diligence",
                "Siguiente pasos y timeline de levantamiento",
            ],
        },
        "parametros_factuales": {
            "contexto": "Firma de asesoría financiera con red de inversionistas y fondos de capital de riesgo",
            "restricciones": [
                "Venture debt solo viable con ronda de equity reciente o comprometida",
                "Dilución de fundadores debe evaluarse en contexto de valoración futura",
            ],
            "metadata": {
                "servicio": "asesoria_startup",
                "tipo_consulta": "financiamiento",
                "etapa": "crecimiento",
            },
        },
        "etiquetas": ["credito", "startup", "venture", "equity", "crecimiento"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de crédito para adquisición de activos fijos",
            "Cliente": "Empresario industrial que necesita financiar compra de maquinaria especializada",
        },
        "objetivo": "Crédito para adquisición de maquinaria industrial con análisis de retorno de inversión",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Especificaciones de la maquinaria a adquirir",
                "Impacto esperado en producción e ingresos",
                "Análisis de retorno de inversión del equipo",
                "Opciones: crédito refaccionario, arrendamiento financiero, leasing",
                "Comparativo de costo financiero total por opción",
                "Beneficios fiscales de cada esquema",
                "Garantías: la propia maquinaria como colateral",
                "Evaluación crediticia de la empresa",
                "Documentación técnica y financiera requerida",
                "Proceso de aprobación y desembolso",
            ],
        },
        "parametros_factuales": {
            "contexto": "Banco de desarrollo con programas de financiamiento para activos productivos",
            "restricciones": [
                "Arrendamiento financiero permite deducción fiscal del total de las rentas",
                "Crédito refaccionario requiere que el bien quede en garantía prendaria",
            ],
            "metadata": {
                "servicio": "credito_empresarial",
                "tipo_credito": "activos_fijos",
                "sector": "industrial",
            },
        },
        "etiquetas": ["credito", "maquinaria", "industrial", "arrendamiento", "activos_fijos"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Consultor de financiamiento de comercio exterior",
            "Cliente": "Exportador que necesita financiamiento para cumplir un pedido internacional grande",
        },
        "objetivo": "Estructuración de financiamiento de pre-exportación para pedido internacional",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Detalle del pedido internacional: producto, destino, monto",
                "Carta de crédito o contrato de compra-venta del importador",
                "Necesidades de financiamiento: materias primas, producción, logística",
                "Opciones de financiamiento de pre-exportación",
                "Carta de crédito como garantía de pago",
                "Seguros de crédito a la exportación",
                "Tipo de cambio y cobertura cambiaria",
                "Apoyo de bancos de desarrollo o programas gubernamentales",
                "Documentación para comercio exterior",
                "Proceso y tiempos desde solicitud hasta desembolso",
            ],
        },
        "parametros_factuales": {
            "contexto": "Banco con división de comercio exterior y corresponsalía internacional",
            "restricciones": [
                "Carta de crédito irrevocable confirmada reduce significativamente el riesgo",
                "Cobertura cambiaria recomendada para plazos mayores a 90 días",
            ],
            "metadata": {
                "servicio": "comercio_exterior",
                "tipo_credito": "pre_exportacion",
                "sector": "exportador",
            },
        },
        "etiquetas": ["credito", "exportacion", "comercio_exterior", "carta_credito", "cambiaria"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "SBA loan specialist at community development financial institution",
            "Client": "Small business owner seeking government-backed loan for expansion",
        },
        "objetivo": "SBA loan application guidance for small business expansion including real estate acquisition",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Business overview and expansion plans",
                "SBA loan programs comparison: 7(a), 504, microloans",
                "Eligibility requirements for each program",
                "Loan amount limits and terms",
                "Down payment and collateral requirements",
                "Personal guarantee and credit score needs",
                "Business plan and financial projection requirements",
                "Application process and timeline",
                "SBA fees and closing costs",
                "Post-approval monitoring and reporting",
            ],
        },
        "parametros_factuales": {
            "contexto": "CDFI with preferred SBA lender status and small business technical assistance",
            "restricciones": [
                "SBA 504 loan requires 10% borrower equity injection for new businesses",
                "Personal guarantee required from all owners with 20%+ stake",
            ],
            "metadata": {
                "servicio": "business_lending",
                "tipo_credito": "sba_loan",
                "programa": "sba_504",
            },
        },
        "etiquetas": ["business_loan", "sba", "expansion", "small_business", "government_backed"],
    },
    # -------------------------------------------------------------------------
    # 41-45: Wealth management
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Wealth manager de banca privada",
            "Cliente": "Empresario exitoso que desea estructurar su patrimonio familiar",
        },
        "objetivo": "Diseño de estructura patrimonial familiar con fideicomisos y plan de sucesión",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 12,
            "turnos_max": 24,
            "flujo_esperado": [
                "Mapeo integral del patrimonio: inmuebles, inversiones, empresas",
                "Objetivos patrimoniales de la familia: preservación, crecimiento, transferencia",
                "Estructura actual de tenencia de activos",
                "Opciones de vehículos patrimoniales: fideicomisos, sociedades, fondos",
                "Plan de sucesión empresarial",
                "Testamentos y voluntades anticipadas",
                "Optimización fiscal de la estructura patrimonial",
                "Protección patrimonial ante contingencias",
                "Gobernanza familiar y protocolo de familia",
                "Filantropía y legado",
                "Implementación por fases y equipo profesional",
                "Revisión periódica y adaptación",
            ],
        },
        "parametros_factuales": {
            "contexto": "Family office con servicios de banca privada, fiscal, legal y sucesión",
            "restricciones": [
                "Estructura patrimonial debe estar alineada con regulación fiscal y anti-lavado",
                "Plan de sucesión debe considerar aspectos emocionales y de gobernanza familiar",
            ],
            "metadata": {
                "servicio": "wealth_management",
                "tipo_consulta": "estructuracion_patrimonial",
                "tipo_cliente": "familia_empresaria",
            },
        },
        "etiquetas": ["patrimonio", "fideicomiso", "sucesion", "familia", "banca_privada"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Gestor de inversiones inmobiliarias",
            "Cliente": "Inversionista que busca diversificar patrimonio con bienes raíces comerciales",
        },
        "objetivo": "Evaluación de oportunidad de inversión inmobiliaria comercial para diversificación patrimonial",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Patrimonio actual y porcentaje en bienes raíces",
                "Objetivos de la inversión inmobiliaria: renta, plusvalía, ambos",
                "Tipos de inmuebles comerciales: oficinas, retail, industrial, mixto",
                "Análisis de mercado y zona geográfica",
                "Cap rate y rendimiento esperado",
                "Estructura de la inversión: directa, FIBRA, fondo",
                "Financiamiento de la adquisición",
                "Implicaciones fiscales y deducibilidad",
                "Administración de la propiedad: propia vs tercero",
                "Due diligence legal y técnica del inmueble",
            ],
        },
        "parametros_factuales": {
            "contexto": "Firma de inversiones inmobiliarias con acceso a propiedades comerciales y FIBRAs",
            "restricciones": [
                "Inversión inmobiliaria no debería superar 30-40% del patrimonio total",
                "Due diligence legal obligatorio antes de cualquier adquisición",
            ],
            "metadata": {
                "servicio": "inversiones_inmobiliarias",
                "tipo_consulta": "oportunidad",
                "segmento": "comercial",
            },
        },
        "etiquetas": ["patrimonio", "inmobiliario", "comercial", "fibra", "diversificacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Asesor de inversiones alternativas",
            "Cliente": "Inversionista sofisticado interesado en private equity y venture capital",
        },
        "objetivo": "Asesoría sobre asignación a inversiones alternativas: private equity y venture capital",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Perfil del inversionista y experiencia con alternativos",
                "Porcentaje actual y propuesto de alternativos en portafolio",
                "Diferencias entre PE, VC, real assets, hedge funds",
                "Horizonte de inversión y compromisos de capital",
                "Estructura de fondo: GP/LP, llamadas de capital, distribuciones",
                "Due diligence del gestor del fondo",
                "Comisiones y estructura de incentivos: 2/20",
                "Riesgo de iliquidez y J-curve",
                "Diversificación por vintage year y estrategia",
                "Requisitos legales y regulatorios para inversionistas calificados",
            ],
        },
        "parametros_factuales": {
            "contexto": "Banca privada con acceso a fondos de inversión alternativa nacionales e internacionales",
            "restricciones": [
                "Inversiones alternativas solo para inversionistas calificados según regulación",
                "Asignación a alternativos típicamente 10-20% del portafolio total",
            ],
            "metadata": {
                "servicio": "inversiones_alternativas",
                "tipo_consulta": "asesoria",
                "instrumentos": "pe_vc",
            },
        },
        "etiquetas": ["patrimonio", "private_equity", "venture_capital", "alternativos", "sofisticado"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Consultor filantrópico de banca privada",
            "Cliente": "Familia adinerada que desea crear una fundación familiar con propósito social",
        },
        "objetivo": "Diseño de estrategia filantrópica familiar con creación de fundación y beneficios fiscales",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Visión y valores filantrópicos de la familia",
                "Causas prioritarias y enfoque geográfico",
                "Opciones: fundación privada, fondo de donaciones, fideicomiso",
                "Estructura legal y gobernanza de la fundación",
                "Patrimonio a asignar y flujo de donaciones",
                "Beneficios fiscales de las donaciones",
                "Inversión de los activos de la fundación",
                "Medición de impacto social",
                "Involucramiento de las siguientes generaciones",
                "Implementación y cronograma",
            ],
        },
        "parametros_factuales": {
            "contexto": "Family office con departamento de filantropía y alianzas con organizaciones sociales",
            "restricciones": [
                "Fundaciones deben obtener autorización de donataria autorizada para deducibilidad",
                "Mínimo de patrimonio y operación anual según regulación de donatarias",
            ],
            "metadata": {
                "servicio": "filantropia",
                "tipo_consulta": "diseno_fundacion",
                "tipo_cliente": "familia_hnwi",
            },
        },
        "etiquetas": ["patrimonio", "filantropia", "fundacion", "impacto_social", "donataria"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Cross-border wealth planning specialist",
            "Client": "Dual-citizen family with assets in multiple countries seeking unified wealth strategy",
        },
        "objetivo": "Cross-border wealth management strategy for family with assets in multiple jurisdictions",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 12,
            "turnos_max": 24,
            "flujo_esperado": [
                "Global asset inventory across jurisdictions",
                "Tax residency determination for each family member",
                "Double taxation treaty applicability analysis",
                "Estate and inheritance tax exposure by jurisdiction",
                "Investment account structuring for tax efficiency",
                "Foreign financial account reporting obligations",
                "Trust and foundation structures across borders",
                "Currency risk management strategy",
                "Cross-border succession planning",
                "Education funding across jurisdictions",
                "Coordination of professional advisors in each country",
                "Implementation roadmap and governance",
            ],
        },
        "parametros_factuales": {
            "contexto": "Global wealth management firm with multi-jurisdictional expertise and advisor network",
            "restricciones": [
                "FATCA and CRS reporting requirements must be fully complied with",
                "Each jurisdiction's anti-money laundering regulations must be satisfied",
            ],
            "metadata": {
                "servicio": "cross_border_wealth",
                "tipo_consulta": "unified_strategy",
                "tipo_cliente": "dual_citizen_family",
            },
        },
        "etiquetas": ["wealth", "cross_border", "multi_jurisdiction", "estate", "tax_planning"],
    },
    # -------------------------------------------------------------------------
    # 46-50: Fraud detection / account security
    # -------------------------------------------------------------------------
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Ejecutivo de seguridad bancaria y prevención de fraude",
            "Cliente": "Cuentahabiente que recibió alerta de intento de acceso no autorizado a su banca en línea",
        },
        "objetivo": "Atención a alerta de seguridad por intento de acceso no autorizado a banca digital",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Verificación de identidad reforzada del cuentahabiente",
                "Confirmación de que el intento de acceso no fue del cliente",
                "Bloqueo inmediato de acceso a banca en línea",
                "Revisión de actividad reciente en todas las cuentas",
                "Identificación de dispositivos autorizados vs sospechosos",
                "Restablecimiento de credenciales de seguridad",
                "Activación de autenticación de dos factores si no existe",
                "Recomendaciones de seguridad digital para el cliente",
            ],
        },
        "parametros_factuales": {
            "contexto": "Centro de seguridad bancaria con monitoreo de transacciones en tiempo real",
            "restricciones": [
                "Bloquear acceso inmediatamente ante confirmación de intento no autorizado",
                "No solicitar contraseñas al cliente, solo guiar el restablecimiento",
            ],
            "metadata": {
                "servicio": "seguridad_bancaria",
                "tipo_consulta": "alerta_seguridad",
                "tipo_amenaza": "acceso_no_autorizado",
            },
        },
        "etiquetas": ["seguridad", "fraude", "acceso_no_autorizado", "banca_digital", "bloqueo"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en prevención de fraude por ingeniería social",
            "Cliente": "Persona que fue víctima de estafa telefónica y realizó transferencia a cuenta fraudulenta",
        },
        "objetivo": "Atención de emergencia por fraude de ingeniería social con intento de recuperación de fondos",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Verificación de identidad del cliente",
                "Documentación detallada del fraude: cronología, montos, cuentas",
                "Bloqueo inmediato de la cuenta para evitar más salidas",
                "Solicitud de retención de fondos a banco receptor",
                "Registro formal de la denuncia interna",
                "Orientación para denuncia ante autoridades",
                "Proceso de investigación y recuperación de fondos",
                "Plazos y probabilidades de recuperación",
                "Medidas de prevención futura",
                "Apoyo emocional y recursos de víctimas de fraude",
            ],
        },
        "parametros_factuales": {
            "contexto": "Unidad de fraudes bancarios con protocolo de respuesta rápida y coordinación interbancaria",
            "restricciones": [
                "Solicitar retención interbancaria dentro de las primeras 24 horas para maximizar recuperación",
                "Denuncia ante ministerio público es requisito para proceso formal de recuperación",
            ],
            "metadata": {
                "servicio": "prevencion_fraude",
                "tipo_consulta": "emergencia_fraude",
                "tipo_fraude": "ingenieria_social",
            },
        },
        "etiquetas": ["seguridad", "fraude", "ingenieria_social", "recuperacion", "emergencia"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Analista de monitoreo de transacciones sospechosas",
            "Cliente": "Cuentahabiente contactado por el banco debido a patrón inusual de transacciones",
        },
        "objetivo": "Verificación de transacciones inusuales detectadas por sistema de monitoreo anti-fraude",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 6,
            "turnos_max": 14,
            "flujo_esperado": [
                "Explicación de por qué se contactó al cliente",
                "Presentación de las transacciones marcadas como inusuales",
                "Verificación con el cliente de cada transacción",
                "Clasificación: legítimas vs sospechosas",
                "Acciones inmediatas si se confirma fraude",
                "Actualización del perfil transaccional si son legítimas",
            ],
        },
        "parametros_factuales": {
            "contexto": "Sistema de monitoreo de transacciones con algoritmos de detección de anomalías",
            "restricciones": [
                "Toda transacción marcada debe ser verificada con el titular antes de bloquear",
                "Actualizar perfil transaccional si el patrón cambió legítimamente",
            ],
            "metadata": {
                "servicio": "monitoreo_fraude",
                "tipo_consulta": "verificacion",
                "deteccion": "algoritmica",
            },
        },
        "etiquetas": ["seguridad", "monitoreo", "transacciones", "anomalia", "verificacion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "es",
        "roles": ["Asesor", "Cliente"],
        "descripcion_roles": {
            "Asesor": "Especialista en seguridad de medios de pago",
            "Cliente": "Comerciante que reporta devoluciones de cargo fraudulentas en su terminal punto de venta",
        },
        "objetivo": "Asesoría a comercio sobre prevención y gestión de chargebacks fraudulentos en TPV",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Análisis de los chargebacks recibidos: montos, frecuencia, motivos",
                "Identificación de patrones: friendly fraud, card not present",
                "Revisión de procesos de aceptación de tarjetas del comercio",
                "Mejores prácticas para prevenir chargebacks",
                "Evidencia necesaria para disputar chargebacks injustificados",
                "Proceso de representamiento ante el procesador",
                "Herramientas de prevención: 3D Secure, AVS, CVV",
                "Plan de acción para reducir tasa de chargebacks",
            ],
        },
        "parametros_factuales": {
            "contexto": "Adquirente de medios de pago con herramientas de prevención y disputas de chargebacks",
            "restricciones": [
                "Tasa de chargebacks superior al 1% puede resultar en penalización por parte de la red de pago",
                "Evidencia de entrega y firma del tarjetahabiente es clave para representamiento exitoso",
            ],
            "metadata": {
                "servicio": "medios_de_pago",
                "tipo_consulta": "prevencion_chargeback",
                "tipo_cliente": "comercio",
            },
        },
        "etiquetas": ["seguridad", "chargeback", "comercio", "tpv", "prevencion"],
    },
    {
        "dominio": "finance.advisory",
        "idioma": "en",
        "roles": ["Advisor", "Client"],
        "descripcion_roles": {
            "Advisor": "Cybersecurity and financial fraud investigator",
            "Client": "Business owner who suspects employee is committing internal financial fraud",
        },
        "objetivo": "Initial assessment and investigation plan for suspected internal financial fraud in a business",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Confidential intake of suspicions and evidence",
                "Types of internal fraud: embezzlement, payroll, vendor, expense",
                "Preservation of digital and physical evidence",
                "Forensic accounting engagement and scope",
                "Internal controls review and gap analysis",
                "Interview strategy for implicated employees",
                "Legal considerations and employee rights",
                "Law enforcement reporting decision",
                "Recovery options: civil action, insurance claim",
                "Remediation: strengthened controls and monitoring",
            ],
        },
        "parametros_factuales": {
            "contexto": "Financial investigation firm with forensic accountants and digital forensics capability",
            "restricciones": [
                "Preserve all evidence and maintain chain of custody from the start",
                "Do not confront suspected employee before investigation plan is established",
            ],
            "metadata": {
                "servicio": "fraud_investigation",
                "tipo_consulta": "internal_fraud",
                "tipo_fraude": "employee_fraud",
            },
        },
        "etiquetas": ["fraud", "internal", "investigation", "forensic", "employee", "controls"],
    },
]
