"""Medical consultation domain — 50 curated seed definitions.

Seeds cover the full spectrum of clinical interactions: general consultations,
medication reviews, lab results, specialist referrals, chronic disease management,
mental health, preventive care, post-surgical follow-up, telemedicine, and triage.

All data is synthetic. No real PII is present.
"""

from __future__ import annotations

MEDICAL_SEEDS: list[dict[str, object]] = [
    # -------------------------------------------------------------------------
    # 1-5: General consultation / symptom assessment
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico general en consulta de primera vez",
            "Paciente": "Adulto con síntomas respiratorios persistentes",
        },
        "objetivo": "Evaluación inicial de síntomas respiratorios de más de dos semanas de evolución",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 20,
            "flujo_esperado": [
                "Saludo y motivo de consulta",
                "Historia del padecimiento actual",
                "Interrogatorio por aparatos y sistemas",
                "Antecedentes personales y familiares relevantes",
                "Exploración física dirigida",
                "Impresión diagnóstica inicial",
                "Solicitud de estudios complementarios",
                "Plan terapéutico y seguimiento",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de medicina general con acceso a laboratorio y gabinete",
            "restricciones": [
                "Seguir guías clínicas vigentes para infección respiratoria",
                "Descartar signos de alarma antes de manejo ambulatorio",
            ],
            "metadata": {
                "especialidad": "medicina_general",
                "tipo_consulta": "primera_vez",
                "sistema_afectado": "respiratorio",
            },
        },
        "etiquetas": ["consulta_general", "respiratorio", "primera_vez", "sintomas"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar en unidad de atención primaria",
            "Paciente": "Persona adulta con cefalea recurrente en las últimas semanas",
        },
        "objetivo": "Evaluación de cefalea recurrente y descarte de banderas rojas neurológicas",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Motivo de consulta y caracterización del dolor",
                "Frecuencia, duración e intensidad de episodios",
                "Factores desencadenantes y atenuantes",
                "Síntomas asociados neurológicos",
                "Antecedentes de migraña familiar",
                "Exploración neurológica básica",
                "Diagnóstico diferencial",
                "Plan de manejo y criterios de alarma",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de medicina familiar con equipo de exploración neurológica básica",
            "restricciones": [
                "Aplicar criterios SNNOOP10 para banderas rojas de cefalea",
                "Derivar a neurología si hay datos de focalización",
            ],
            "metadata": {
                "especialidad": "medicina_familiar",
                "tipo_consulta": "evaluacion",
                "sistema_afectado": "neurologico",
            },
        },
        "etiquetas": ["consulta_general", "cefalea", "neurologia", "banderas_rojas"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico general en clínica ambulatoria",
            "Paciente": "Persona con dolor abdominal intermitente desde hace una semana",
        },
        "objetivo": "Evaluación de dolor abdominal subagudo con exploración física y plan diagnóstico",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Motivo de consulta y localización del dolor",
                "Características del dolor: tipo, irradiación, intensidad",
                "Síntomas gastrointestinales asociados",
                "Hábitos alimenticios y cambios recientes",
                "Exploración abdominal completa",
                "Diagnósticos diferenciales",
                "Estudios de laboratorio e imagen solicitados",
                "Tratamiento sintomático y cita de seguimiento",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica ambulatoria con acceso a ultrasonido y laboratorio básico",
            "restricciones": [
                "Descartar abdomen agudo antes de indicar manejo ambulatorio",
                "Referir a urgencias si hay signos peritoneales",
            ],
            "metadata": {
                "especialidad": "medicina_general",
                "tipo_consulta": "evaluacion",
                "sistema_afectado": "gastrointestinal",
            },
        },
        "etiquetas": ["consulta_general", "dolor_abdominal", "gastrointestinal", "diagnostico"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar de atención primaria",
            "Paciente": "Adulto joven con fatiga crónica y pérdida de peso involuntaria",
        },
        "objetivo": "Abordaje integral de fatiga crónica con pérdida de peso para descarte de patología sistémica",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Motivo de consulta y cronología de síntomas",
                "Cuantificación de pérdida de peso y período",
                "Revisión por sistemas completa",
                "Hábitos de sueño, alimentación y actividad física",
                "Estado emocional y estrés laboral",
                "Antecedentes personales y familiares",
                "Exploración física completa",
                "Panel de laboratorios amplio",
                "Diagnósticos diferenciales priorizados",
                "Plan de seguimiento y derivación si necesario",
            ],
        },
        "parametros_factuales": {
            "contexto": "Centro de atención primaria con capacidad de laboratorio amplio y referencia a especialistas",
            "restricciones": [
                "Pérdida involuntaria de más del 5% del peso corporal requiere evaluación exhaustiva",
                "Incluir tamizaje tiroideo, metabólico y marcadores inflamatorios",
            ],
            "metadata": {
                "especialidad": "medicina_familiar",
                "tipo_consulta": "evaluacion_integral",
                "sintomas": "fatiga_perdida_peso",
            },
        },
        "etiquetas": ["consulta_general", "fatiga", "perdida_peso", "evaluacion_integral"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Primary care physician in outpatient clinic",
            "Patient": "Middle-aged adult presenting with persistent lower back pain",
        },
        "objetivo": "Assessment of chronic lower back pain with functional impact evaluation",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Chief complaint and pain characterization",
                "Duration, triggers, and aggravating factors",
                "Impact on daily activities and work",
                "Red flag screening for cauda equina and malignancy",
                "Musculoskeletal examination",
                "Imaging and lab recommendations",
                "Conservative management plan",
                "Referral criteria discussion",
            ],
        },
        "parametros_factuales": {
            "contexto": "Outpatient primary care clinic with imaging referral capability",
            "restricciones": [
                "Follow evidence-based guidelines for acute vs chronic back pain management",
                "Screen for red flags before conservative management",
            ],
            "metadata": {
                "especialidad": "primary_care",
                "tipo_consulta": "evaluation",
                "sistema_afectado": "musculoskeletal",
            },
        },
        "etiquetas": ["general_consultation", "back_pain", "musculoskeletal", "assessment"],
    },
    # -------------------------------------------------------------------------
    # 6-10: Medication review / prescription renewal
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico internista responsable de ajuste terapéutico",
            "Paciente": "Adulto mayor con polifarmacia por múltiples comorbilidades",
        },
        "objetivo": "Revisión integral de medicamentos para optimizar esquema terapéutico y reducir polifarmacia",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Revisión de lista completa de medicamentos actuales",
                "Verificación de indicación vigente para cada fármaco",
                "Evaluación de adherencia terapéutica",
                "Identificación de interacciones medicamentosas",
                "Evaluación de efectos adversos reportados",
                "Propuesta de simplificación de esquema",
                "Ajuste de dosis según función renal y hepática",
                "Educación sobre cambios realizados",
                "Entrega de esquema terapéutico actualizado",
                "Cita de seguimiento en 2 semanas",
            ],
        },
        "parametros_factuales": {
            "contexto": (
                "Consulta de medicina interna con acceso a expediente electrónico y herramientas de interacciones"
            ),
            "restricciones": [
                "Aplicar criterios STOPP/START para medicación inapropiada en adulto mayor",
                "No suspender medicamentos críticos sin titulación gradual",
            ],
            "metadata": {
                "especialidad": "medicina_interna",
                "tipo_consulta": "revision_medicamentos",
                "perfil_paciente": "adulto_mayor_polifarmacia",
            },
        },
        "etiquetas": ["medicamentos", "polifarmacia", "revision", "adulto_mayor", "interacciones"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar que renueva recetas crónicas",
            "Paciente": "Persona con hipertensión arterial controlada que solicita renovación de receta",
        },
        "objetivo": "Renovación de receta de antihipertensivo con verificación de control adecuado",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 6,
            "turnos_max": 14,
            "flujo_esperado": [
                "Verificación de adherencia al tratamiento",
                "Registro de cifras tensionales recientes",
                "Revisión de efectos secundarios",
                "Evaluación de estilo de vida",
                "Renovación de receta con ajustes si necesario",
                "Solicitud de estudios de control periódico",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de medicina familiar con baumanómetro calibrado y expediente electrónico",
            "restricciones": [
                "Renovación de receta solo si última consulta fue hace menos de 3 meses",
                "Solicitar laboratorios de control cada 6 meses mínimo",
            ],
            "metadata": {
                "especialidad": "medicina_familiar",
                "tipo_consulta": "renovacion_receta",
                "padecimiento": "hipertension_arterial",
            },
        },
        "etiquetas": ["medicamentos", "renovacion", "hipertension", "cronico", "control"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico tratante de endocrinología",
            "Paciente": "Persona con diabetes tipo 2 que requiere ajuste de insulina",
        },
        "objetivo": "Ajuste de esquema de insulina por control glucémico subóptimo a pesar de tratamiento oral",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Revisión de valores de hemoglobina glucosilada",
                "Análisis de automonitoreo de glucosa",
                "Evaluación de tratamiento oral actual",
                "Explicación de la necesidad de insulinización",
                "Tipos de insulina y esquemas disponibles",
                "Técnica de aplicación y rotación de sitios",
                "Manejo de hipoglucemia",
                "Plan de automonitoreo intensificado",
                "Educación nutricional complementaria",
                "Cita de control en 1-2 semanas",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consulta de endocrinología con equipo de educación en diabetes",
            "restricciones": [
                "Iniciar insulina si HbA1c mayor a 9% a pesar de doble terapia oral",
                "Titular dosis cada 3 días según monitoreo capilar",
            ],
            "metadata": {
                "especialidad": "endocrinologia",
                "tipo_consulta": "ajuste_tratamiento",
                "padecimiento": "diabetes_tipo_2",
            },
        },
        "etiquetas": ["medicamentos", "insulina", "diabetes", "ajuste", "glucosa"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Psiquiatra responsable de ajuste de psicofármacos",
            "Paciente": "Persona en tratamiento antidepresivo que reporta efectos secundarios",
        },
        "objetivo": "Evaluación de efectos adversos de antidepresivo y posible cambio o ajuste de dosis",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Exploración de síntomas actuales del paciente",
                "Evaluación de respuesta terapéutica",
                "Detalle de efectos adversos experimentados",
                "Valoración de riesgo-beneficio del tratamiento actual",
                "Opciones de ajuste: dosis, horario, cambio de fármaco",
                "Discusión de expectativas y tiempo de respuesta",
                "Nuevo plan terapéutico",
                "Seguimiento cercano y señales de alerta",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consulta de psiquiatría con enfoque de toma de decisiones compartida",
            "restricciones": [
                "Evaluar ideación suicida en cada consulta de seguimiento psiquiátrico",
                "Cambios de antidepresivo requieren cross-titration gradual",
            ],
            "metadata": {
                "especialidad": "psiquiatria",
                "tipo_consulta": "ajuste_medicamento",
                "padecimiento": "depresion",
            },
        },
        "etiquetas": ["medicamentos", "antidepresivo", "efectos_adversos", "ajuste", "psiquiatria"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Primary care doctor managing chronic medications",
            "Patient": "Adult requesting renewal of cholesterol-lowering medication",
        },
        "objetivo": "Statin prescription renewal with lipid panel review and cardiovascular risk assessment",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 6,
            "turnos_max": 14,
            "flujo_esperado": [
                "Medication adherence verification",
                "Review of most recent lipid panel results",
                "Assessment of any muscle-related side effects",
                "Cardiovascular risk factor update",
                "Prescription renewal or dose adjustment",
                "Next lab work and follow-up scheduling",
            ],
        },
        "parametros_factuales": {
            "contexto": "Primary care office with integrated electronic health records and lab results",
            "restricciones": [
                "Check liver function and CK if myalgia reported",
                "Lipid panel required at least annually for statin monitoring",
            ],
            "metadata": {
                "especialidad": "primary_care",
                "tipo_consulta": "prescription_renewal",
                "padecimiento": "hyperlipidemia",
            },
        },
        "etiquetas": ["medication", "statin", "cholesterol", "renewal", "cardiovascular"],
    },
    # -------------------------------------------------------------------------
    # 11-15: Lab results discussion
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico internista que interpreta resultados de laboratorio",
            "Paciente": "Adulto que acude a revisión de resultados de biometría hemática y química sanguínea",
        },
        "objetivo": "Explicación de resultados de laboratorio rutinario con hallazgo de anemia leve",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Revisión general de resultados normales",
                "Identificación de valores fuera de rango",
                "Explicación de la anemia detectada en términos comprensibles",
                "Posibles causas a investigar",
                "Estudios complementarios necesarios",
                "Recomendaciones nutricionales iniciales",
                "Plan de suplementación si aplica",
                "Cita de seguimiento con resultados completos",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio con acceso a resultados electrónicos de laboratorio",
            "restricciones": [
                "Explicar resultados en lenguaje accesible para el paciente",
                "No alarmar innecesariamente por hallazgos leves",
            ],
            "metadata": {
                "especialidad": "medicina_interna",
                "tipo_consulta": "revision_resultados",
                "hallazgo": "anemia_leve",
            },
        },
        "etiquetas": ["laboratorio", "resultados", "anemia", "biometria", "explicacion"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Endocrinólogo interpretando perfil tiroideo",
            "Paciente": "Persona con sospecha de hipotiroidismo referida por médico general",
        },
        "objetivo": "Discusión de perfil tiroideo alterado con diagnóstico de hipotiroidismo subclínico",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Revisión de síntomas que motivaron el estudio",
                "Presentación de valores de TSH y T4 libre",
                "Explicación del hipotiroidismo subclínico",
                "Diferencia con hipotiroidismo clínico",
                "Factores de riesgo y asociaciones",
                "Decisión terapéutica: observar vs tratar",
                "Educación sobre monitoreo y pronóstico",
                "Plan de seguimiento y controles periódicos",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consulta de endocrinología con resultados de perfil tiroideo completo",
            "restricciones": [
                "TSH entre 4.5-10 mUI/L requiere evaluar síntomas antes de iniciar levotiroxina",
                "Confirmar con segunda determinación antes de diagnosticar",
            ],
            "metadata": {
                "especialidad": "endocrinologia",
                "tipo_consulta": "revision_resultados",
                "hallazgo": "hipotiroidismo_subclinico",
            },
        },
        "etiquetas": ["laboratorio", "tiroides", "hipotiroidismo", "tsh", "endocrinologia"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar interpretando panel metabólico",
            "Paciente": "Adulto con factores de riesgo cardiovascular en revisión de glucosa y lípidos",
        },
        "objetivo": "Comunicación de resultados con glucosa en ayuno alterada y dislipidemia mixta",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Contexto del chequeo y factores de riesgo previos",
                "Presentación de valores de glucosa en ayuno",
                "Explicación de estado prediabético",
                "Presentación de perfil lipídico completo",
                "Explicación de dislipidemia y riesgo cardiovascular",
                "Cálculo de riesgo cardiovascular a 10 años",
                "Plan de cambios en estilo de vida",
                "Decisión sobre inicio de tratamiento farmacológico",
                "Metas terapéuticas claras y medibles",
                "Seguimiento con laboratorios en 3 meses",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de medicina familiar con calculadora de riesgo cardiovascular integrada",
            "restricciones": [
                "Glucosa en ayuno entre 100-125 mg/dL clasifica como prediabetes según ADA",
                "Decisión de estatina basada en riesgo cardiovascular global, no solo LDL",
            ],
            "metadata": {
                "especialidad": "medicina_familiar",
                "tipo_consulta": "revision_resultados",
                "hallazgos": "prediabetes_dislipidemia",
            },
        },
        "etiquetas": ["laboratorio", "glucosa", "lipidos", "prediabetes", "riesgo_cardiovascular"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Nefrólogo que revisa función renal",
            "Paciente": "Persona con diabetes e hipertensión con creatinina elevada detectada en control",
        },
        "objetivo": "Discusión de deterioro de función renal detectado en laboratorios de control de crónicos",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Presentación de valores de creatinina y TFG estimada",
                "Explicación de la enfermedad renal crónica",
                "Clasificación del estadio actual",
                "Relación con diabetes e hipertensión",
                "Implicaciones para medicamentos actuales",
                "Ajuste de dosis de fármacos nefrotóxicos",
                "Recomendaciones dietéticas nefrológicas",
                "Metas de control de presión arterial y glucosa",
                "Estudios complementarios: proteinuria, ultrasonido renal",
                "Frecuencia de seguimiento nefrológico",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consulta de nefrología con herramientas de cálculo de TFG y clasificación KDIGO",
            "restricciones": [
                "Clasificar según KDIGO: TFG y albuminuria",
                "Suspender metformina si TFG menor a 30 mL/min",
            ],
            "metadata": {
                "especialidad": "nefrologia",
                "tipo_consulta": "revision_resultados",
                "hallazgo": "enfermedad_renal_cronica",
            },
        },
        "etiquetas": ["laboratorio", "renal", "creatinina", "erc", "diabetes", "hipertension"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Oncologist reviewing tumor marker results",
            "Patient": "Cancer survivor receiving routine post-treatment surveillance labs",
        },
        "objetivo": "Discussion of post-treatment surveillance lab results including tumor markers within normal range",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Review of overall surveillance lab panel",
                "Tumor marker results and trends over time",
                "Comparison with previous values",
                "Reassurance about normal findings",
                "Discussion of next imaging studies",
                "Emotional support and survivorship care",
                "Schedule for next surveillance visit",
                "Signs and symptoms to watch for",
            ],
        },
        "parametros_factuales": {
            "contexto": "Oncology follow-up clinic with longitudinal lab tracking system",
            "restricciones": [
                "Present results in context of overall trend, not isolated values",
                "Address patient anxiety about recurrence proactively",
            ],
            "metadata": {
                "especialidad": "oncology",
                "tipo_consulta": "surveillance_results",
                "hallazgo": "tumor_markers_normal",
            },
        },
        "etiquetas": ["lab_results", "oncology", "tumor_markers", "surveillance", "survivorship"],
    },
    # -------------------------------------------------------------------------
    # 16-20: Specialist referral
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico general que refiere a especialista",
            "Paciente": "Persona con sospecha de síndrome metabólico que requiere evaluación especializada",
        },
        "objetivo": "Referencia a endocrinología por síndrome metabólico con múltiples factores de riesgo",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Resumen del cuadro clínico actual",
                "Explicación del síndrome metabólico",
                "Justificación de la referencia a endocrinología",
                "Qué esperar en la consulta especializada",
                "Estudios que debe llevar a la cita",
                "Mantenimiento del tratamiento actual mientras tanto",
                "Proceso administrativo de la referencia",
                "Compromiso de seguimiento coordinado",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de primer nivel con sistema de referencia electrónica a segundo nivel",
            "restricciones": [
                "Referencia debe incluir resumen clínico completo y estudios previos",
                "No suspender tratamiento actual sin indicación del especialista",
            ],
            "metadata": {
                "especialidad": "medicina_general",
                "tipo_consulta": "referencia",
                "destino": "endocrinologia",
                "motivo": "sindrome_metabolico",
            },
        },
        "etiquetas": ["referencia", "endocrinologia", "sindrome_metabolico", "coordinacion"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar coordinando referencia urgente",
            "Paciente": "Persona con hallazgo incidental en radiografía que requiere evaluación por neumología",
        },
        "objetivo": "Referencia urgente a neumología por nódulo pulmonar incidental detectado en radiografía",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Comunicación del hallazgo al paciente con sensibilidad",
                "Explicación de qué es un nódulo pulmonar",
                "Aclarar que la mayoría son benignos pero requieren estudio",
                "Justificación de la referencia urgente a neumología",
                "Estudios adicionales previos a la cita",
                "Manejo de la ansiedad del paciente",
                "Coordinación de cita prioritaria",
                "Plan de comunicación entre niveles de atención",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de medicina familiar con protocolo de hallazgos incidentales",
            "restricciones": [
                "Nódulos pulmonares mayores de 8mm requieren evaluación prioritaria",
                "Comunicar hallazgo con empatía, sin minimizar ni alarmar",
            ],
            "metadata": {
                "especialidad": "medicina_familiar",
                "tipo_consulta": "referencia_urgente",
                "destino": "neumologia",
                "hallazgo": "nodulo_pulmonar",
            },
        },
        "etiquetas": ["referencia", "neumologia", "nodulo_pulmonar", "urgente", "incidental"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Pediatra que refiere a especialista pediátrico",
            "Paciente": "Padre o madre de menor con retraso en el desarrollo psicomotor",
        },
        "objetivo": "Referencia a neurología pediátrica por retraso del desarrollo detectado en control del niño sano",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Revisión de hitos del desarrollo alcanzados",
                "Identificación de áreas de retraso",
                "Explicación empática a los padres",
                "Importancia de evaluación neurológica temprana",
                "Qué esperar en la consulta de neurología pediátrica",
                "Estudios preliminares a solicitar",
                "Intervención temprana mientras se espera cita",
                "Apoyo emocional a la familia",
                "Proceso de referencia y tiempos",
                "Red de apoyo disponible",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio pediátrico con escalas de desarrollo estandarizadas",
            "restricciones": [
                "Usar escalas validadas para documentar el retraso del desarrollo",
                "Referencia a estimulación temprana simultánea a evaluación neurológica",
            ],
            "metadata": {
                "especialidad": "pediatria",
                "tipo_consulta": "referencia",
                "destino": "neurologia_pediatrica",
                "motivo": "retraso_desarrollo",
            },
        },
        "etiquetas": ["referencia", "pediatria", "neurologia", "desarrollo", "estimulacion_temprana"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Ginecólogo que refiere a oncología",
            "Paciente": "Mujer con resultado anormal de Papanicolaou que requiere colposcopía",
        },
        "objetivo": "Referencia a colposcopía por resultado de Papanicolaou con lesión intraepitelial",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Explicación del resultado del Papanicolaou",
                "Qué significa la lesión intraepitelial",
                "Aclarar que no es cáncer pero requiere seguimiento",
                "Explicación del procedimiento de colposcopía",
                "Preparación para el estudio",
                "Posibles resultados y siguientes pasos",
                "Manejo de la ansiedad de la paciente",
                "Programación de la colposcopía",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio ginecológico con protocolo de tamizaje cervical y referencia",
            "restricciones": [
                "LEIBG requiere colposcopía según guías de práctica clínica",
                "Informar que la mayoría de las lesiones de bajo grado regresan espontáneamente",
            ],
            "metadata": {
                "especialidad": "ginecologia",
                "tipo_consulta": "referencia",
                "destino": "colposcopia",
                "hallazgo": "lesion_intraepitelial_bajo_grado",
            },
        },
        "etiquetas": ["referencia", "ginecologia", "papanicolaou", "colposcopia", "tamizaje"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Primary care physician initiating cardiology referral",
            "Patient": "Adult with new-onset atrial fibrillation detected during routine ECG",
        },
        "objetivo": "Referral to cardiology for new-onset atrial fibrillation management and anticoagulation decision",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "ECG findings explanation in patient-friendly terms",
                "What atrial fibrillation means for the heart",
                "Stroke risk assessment using CHA2DS2-VASc",
                "Immediate rate control measures",
                "Why cardiology referral is needed",
                "What to expect at the cardiology visit",
                "Interim precautions and warning signs",
                "Referral process and timeline",
            ],
        },
        "parametros_factuales": {
            "contexto": "Primary care office with ECG capability and electronic referral system",
            "restricciones": [
                "Start rate control if resting heart rate above 110 bpm",
                "Calculate CHA2DS2-VASc score to document in referral",
            ],
            "metadata": {
                "especialidad": "primary_care",
                "tipo_consulta": "referral",
                "destino": "cardiology",
                "hallazgo": "atrial_fibrillation",
            },
        },
        "etiquetas": ["referral", "cardiology", "atrial_fibrillation", "ecg", "anticoagulation"],
    },
    # -------------------------------------------------------------------------
    # 21-25: Chronic disease management
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Internista especializado en control de diabetes",
            "Paciente": "Persona con diabetes tipo 2 de 5 años de evolución en control trimestral",
        },
        "objetivo": "Consulta trimestral de control de diabetes tipo 2 con revisión integral de complicaciones",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Revisión de automonitoreo de glucosa del trimestre",
                "Resultado de hemoglobina glucosilada",
                "Evaluación de cumplimiento de metas glucémicas",
                "Revisión de pies y sensibilidad periférica",
                "Revisión oftalmológica anual pendiente",
                "Control de presión arterial y perfil lipídico",
                "Evaluación de función renal",
                "Ajustes al plan de alimentación",
                "Actividad física y estado emocional",
                "Ajuste terapéutico y próximo control",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de diabetes con equipo multidisciplinario integrado",
            "restricciones": [
                "HbA1c meta menor a 7% para la mayoría de los pacientes adultos",
                "Revisión de pies obligatoria en cada consulta trimestral",
            ],
            "metadata": {
                "especialidad": "medicina_interna",
                "tipo_consulta": "control_periodico",
                "padecimiento": "diabetes_tipo_2",
                "frecuencia": "trimestral",
            },
        },
        "etiquetas": ["cronico", "diabetes", "control", "hba1c", "complicaciones"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Cardiólogo en seguimiento de insuficiencia cardíaca",
            "Paciente": "Persona con insuficiencia cardíaca clase funcional II en control mensual",
        },
        "objetivo": "Control mensual de insuficiencia cardíaca con ajuste de tratamiento diurético",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Evaluación de síntomas: disnea, edema, ortopnea",
                "Control de peso diario y tendencia",
                "Registro de ingesta de líquidos",
                "Evaluación de clase funcional actual",
                "Revisión de signos vitales y auscultación",
                "Resultados de péptido natriurético",
                "Ajuste de diuréticos según volemia",
                "Revisión de medicamentos de base",
                "Educación sobre signos de descompensación",
                "Próxima cita y estudios de seguimiento",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de insuficiencia cardíaca con monitoreo remoto de peso y síntomas",
            "restricciones": [
                "Ganancia de peso mayor a 2 kg en 3 días es señal de retención de líquidos",
                "Mantener tratamiento con IECA/ARA2, betabloqueador y antialdosterónico",
            ],
            "metadata": {
                "especialidad": "cardiologia",
                "tipo_consulta": "control_periodico",
                "padecimiento": "insuficiencia_cardiaca",
                "clase_funcional": "II",
            },
        },
        "etiquetas": ["cronico", "insuficiencia_cardiaca", "control", "diureticos", "peso"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Reumatólogo que maneja artritis reumatoide",
            "Paciente": "Persona con artritis reumatoide en tratamiento con metotrexato",
        },
        "objetivo": "Evaluación de actividad de artritis reumatoide y decisión sobre escalamiento terapéutico",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Evaluación de rigidez matutina y articulaciones afectadas",
                "Aplicación de índice de actividad de enfermedad DAS28",
                "Revisión de reactantes de fase aguda",
                "Tolerancia al metotrexato y efectos adversos",
                "Evaluación de función hepática bajo tratamiento",
                "Discusión de metas terapéuticas no alcanzadas",
                "Opciones de escalamiento: biológico vs combinación",
                "Riesgo-beneficio de terapia biológica",
                "Tamizaje pre-biológico si aplica",
                "Decisión compartida y plan de acción",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consulta de reumatología con acceso a índices de actividad de enfermedad",
            "restricciones": [
                "DAS28 mayor a 3.2 después de 3 meses con metotrexato óptimo justifica escalamiento",
                "Tamizaje de tuberculosis obligatorio antes de iniciar biológico",
            ],
            "metadata": {
                "especialidad": "reumatologia",
                "tipo_consulta": "control_periodico",
                "padecimiento": "artritis_reumatoide",
                "tratamiento_actual": "metotrexato",
            },
        },
        "etiquetas": ["cronico", "artritis_reumatoide", "biologico", "das28", "escalamiento"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Neumólogo que controla asma persistente",
            "Paciente": "Adulto joven con asma moderada persistente mal controlada",
        },
        "objetivo": "Revisión de control de asma y escalonamiento de terapia de mantenimiento",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Evaluación de síntomas con cuestionario ACT",
                "Frecuencia de uso de rescate en último mes",
                "Limitación de actividades por asma",
                "Despertares nocturnos por síntomas",
                "Técnica de inhalación: revisión y corrección",
                "Adherencia al tratamiento de mantenimiento",
                "Espirometría de control",
                "Ajuste de esquema según nivel de control GINA",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de neumología con espirometría y educación en uso de inhaladores",
            "restricciones": [
                "ACT score menor a 20 indica asma mal controlada",
                "Escalonar según guía GINA antes de agregar biológico",
            ],
            "metadata": {
                "especialidad": "neumologia",
                "tipo_consulta": "control_periodico",
                "padecimiento": "asma_persistente",
                "severidad": "moderada",
            },
        },
        "etiquetas": ["cronico", "asma", "inhaladores", "gina", "espirometria", "control"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Gastroenterologist managing inflammatory bowel disease",
            "Patient": "Young adult with Crohn disease in clinical remission on biologic therapy",
        },
        "objetivo": "Routine follow-up for Crohn disease in remission with biologic therapy monitoring",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Symptom review and quality of life assessment",
                "Stool frequency and consistency evaluation",
                "Extraintestinal manifestation screening",
                "Lab results: CRP, calprotectin, drug levels",
                "Biologic therapy tolerance and adherence",
                "Colorectal cancer surveillance discussion",
                "Bone health and nutritional status",
                "Plan for next endoscopic evaluation",
            ],
        },
        "parametros_factuales": {
            "contexto": "IBD specialty clinic with therapeutic drug monitoring capabilities",
            "restricciones": [
                "Fecal calprotectin below 250 supports clinical remission",
                "Therapeutic drug monitoring recommended every 6-12 months",
            ],
            "metadata": {
                "especialidad": "gastroenterology",
                "tipo_consulta": "periodic_control",
                "padecimiento": "crohn_disease",
                "estado": "remission",
            },
        },
        "etiquetas": ["chronic", "crohn", "biologic", "remission", "ibd", "monitoring"],
    },
    # -------------------------------------------------------------------------
    # 26-30: Mental health screening
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar con entrenamiento en salud mental",
            "Paciente": "Adulto que consulta por insomnio pero muestra signos de depresión",
        },
        "objetivo": "Tamizaje de depresión en paciente que consulta por insomnio como síntoma principal",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Exploración del insomnio: inicio, patrón, impacto",
                "Higiene de sueño y factores ambientales",
                "Transición natural a estado emocional",
                "Aplicación de PHQ-9 de forma conversacional",
                "Exploración de anhedonia y estado de ánimo",
                "Evaluación de riesgo suicida",
                "Psicoeducación sobre depresión y su relación con el sueño",
                "Opciones de tratamiento: psicoterapia y farmacología",
                "Referencia a salud mental si necesario",
                "Plan de seguimiento cercano",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de medicina familiar con protocolos de tamizaje de salud mental",
            "restricciones": [
                "PHQ-9 mayor o igual a 10 requiere intervención activa",
                "Evaluación de riesgo suicida obligatoria si PHQ-9 positivo en ítem 9",
            ],
            "metadata": {
                "especialidad": "medicina_familiar",
                "tipo_consulta": "tamizaje",
                "area": "salud_mental",
                "instrumento": "phq9",
            },
        },
        "etiquetas": ["salud_mental", "depresion", "tamizaje", "insomnio", "phq9"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Psiquiatra en primera consulta",
            "Paciente": "Persona referida por ansiedad generalizada que interfiere con su trabajo",
        },
        "objetivo": "Primera evaluación psiquiátrica por trastorno de ansiedad generalizada",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 12,
            "turnos_max": 24,
            "flujo_esperado": [
                "Construcción de rapport y encuadre de la consulta",
                "Motivo de consulta y expectativas del paciente",
                "Exploración de síntomas ansiosos: preocupaciones, tensión, irritabilidad",
                "Duración y patrón temporal de los síntomas",
                "Impacto funcional: laboral, social, familiar",
                "Antecedentes psiquiátricos personales y familiares",
                "Consumo de sustancias",
                "Exploración del estado mental",
                "Diagnóstico diferencial",
                "Formulación diagnóstica y explicación al paciente",
                "Plan terapéutico: psicofármaco y psicoterapia",
                "Educación sobre el trastorno y pronóstico",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consulta de psiquiatría ambulatoria con enfoque biopsicosocial",
            "restricciones": [
                "Aplicar criterios DSM-5 para trastorno de ansiedad generalizada",
                "Descartar causas orgánicas de ansiedad: tiroides, cafeína, sustancias",
            ],
            "metadata": {
                "especialidad": "psiquiatria",
                "tipo_consulta": "primera_vez",
                "diagnostico_presuntivo": "ansiedad_generalizada",
            },
        },
        "etiquetas": ["salud_mental", "ansiedad", "psiquiatria", "primera_vez", "dsm5"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Psicólogo clínico en evaluación de estrés postraumático",
            "Paciente": "Persona que sufrió accidente vial hace 3 meses con síntomas persistentes",
        },
        "objetivo": "Evaluación clínica de posible trastorno de estrés postraumático y plan de intervención",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Encuadre terapéutico y ambiente seguro",
                "Narrativa del evento traumático a ritmo del paciente",
                "Exploración de reexperimentación: flashbacks, pesadillas",
                "Síntomas de evitación",
                "Hiperactivación y estado de alerta",
                "Alteraciones cognitivas y del ánimo",
                "Impacto funcional actual",
                "Aplicación de escala PCL-5",
                "Formulación clínica",
                "Plan de tratamiento: terapia centrada en el trauma",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de salud mental con protocolos de atención al trauma",
            "restricciones": [
                "No forzar la narrativa del trauma en primera sesión",
                "Aplicar PCL-5 como instrumento de apoyo diagnóstico",
            ],
            "metadata": {
                "especialidad": "psicologia_clinica",
                "tipo_consulta": "evaluacion",
                "area": "trauma",
                "instrumento": "pcl5",
            },
        },
        "etiquetas": ["salud_mental", "tept", "trauma", "evaluacion", "pcl5"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Pediatra evaluando conducta en adolescente",
            "Paciente": "Padre/madre de adolescente con cambios de conducta y bajo rendimiento escolar",
        },
        "objetivo": "Tamizaje de salud mental en adolescente con cambios conductuales reportados por los padres",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Entrevista inicial con padres: preocupaciones y observaciones",
                "Contexto escolar y social del adolescente",
                "Entrevista confidencial con el adolescente",
                "Exploración de estado emocional y relaciones",
                "Tamizaje de uso de sustancias",
                "Tamizaje de ideación suicida y autolesiones",
                "Uso de redes sociales y ciberbullying",
                "Evaluación de dinámica familiar",
                "Formulación y diagnóstico diferencial",
                "Plan de intervención y referencia si necesario",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio pediátrico con protocolos de tamizaje adolescente y confidencialidad",
            "restricciones": [
                "Entrevista confidencial con el adolescente es obligatoria a partir de 12 años",
                "Romper confidencialidad solo si hay riesgo inminente de daño",
            ],
            "metadata": {
                "especialidad": "pediatria",
                "tipo_consulta": "tamizaje",
                "area": "salud_mental_adolescente",
                "grupo_etario": "adolescente",
            },
        },
        "etiquetas": ["salud_mental", "adolescente", "tamizaje", "conducta", "pediatria"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Primary care physician with mental health training",
            "Patient": "Working professional presenting with burnout symptoms and work-related stress",
        },
        "objetivo": "Burnout screening and differentiation from major depressive disorder",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Exploration of work situation and stressors",
                "Symptom characterization: exhaustion, cynicism, reduced efficacy",
                "Sleep, appetite, and concentration assessment",
                "PHQ-9 and GAD-7 screening",
                "Differentiation between burnout and depression",
                "Occupational factors and coping mechanisms",
                "Treatment plan: lifestyle, therapy, possible medication",
                "Work accommodations and follow-up plan",
            ],
        },
        "parametros_factuales": {
            "contexto": "Primary care clinic with integrated behavioral health services",
            "restricciones": [
                "Burnout is not a DSM-5 diagnosis but has ICD-11 code QD85",
                "Screen for comorbid depression and anxiety with validated tools",
            ],
            "metadata": {
                "especialidad": "primary_care",
                "tipo_consulta": "screening",
                "area": "mental_health",
                "focus": "burnout",
            },
        },
        "etiquetas": ["mental_health", "burnout", "depression", "screening", "occupational"],
    },
    # -------------------------------------------------------------------------
    # 31-35: Preventive care / vaccination
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Pediatra en consulta de niño sano",
            "Paciente": "Padre/madre con lactante de 6 meses para vacunación y control de crecimiento",
        },
        "objetivo": "Control de niño sano de 6 meses con vacunación según esquema nacional y evaluación del desarrollo",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Somatometría: peso, talla, perímetro cefálico",
                "Evaluación de curvas de crecimiento",
                "Hitos del desarrollo a los 6 meses",
                "Alimentación: inicio de ablactación",
                "Vacunas correspondientes a los 6 meses",
                "Explicación de reacciones esperadas post-vacuna",
                "Evaluación de signos de alarma",
                "Orientación sobre estimulación temprana",
                "Prevención de accidentes en esta etapa",
                "Próxima cita de control y vacunación",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio pediátrico con cartilla de vacunación y curvas de crecimiento OMS",
            "restricciones": [
                "Seguir esquema nacional de vacunación vigente",
                "No vacunar si hay fiebre mayor a 38.5°C o enfermedad aguda",
            ],
            "metadata": {
                "especialidad": "pediatria",
                "tipo_consulta": "control_nino_sano",
                "edad": "6_meses",
                "vacunas": "esquema_6_meses",
            },
        },
        "etiquetas": ["preventivo", "vacunacion", "nino_sano", "desarrollo", "lactante"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico preventivo en programa de detección",
            "Paciente": "Mujer de 40+ años que acude a tamizaje de cáncer de mama",
        },
        "objetivo": "Consulta de tamizaje mamario con mastografía y educación en autoexploración",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Antecedentes familiares de cáncer de mama",
                "Factores de riesgo personales",
                "Exploración clínica mamaria",
                "Indicación de mastografía de tamizaje",
                "Explicación del procedimiento y preparación",
                "Enseñanza de técnica de autoexploración",
                "Frecuencia recomendada de estudios",
                "Entrega de resultados y seguimiento",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de medicina preventiva con servicio de mastografía y programa de detección",
            "restricciones": [
                "Mastografía de tamizaje recomendada anual o bianual a partir de 40 años según guía",
                "Mujeres con antecedente familiar de primer grado iniciar tamizaje 10 años antes del caso índice",
            ],
            "metadata": {
                "especialidad": "medicina_preventiva",
                "tipo_consulta": "tamizaje",
                "programa": "deteccion_cancer_mama",
            },
        },
        "etiquetas": ["preventivo", "cancer_mama", "mastografia", "tamizaje", "autoexploracion"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico de medicina del viajero",
            "Paciente": "Persona que planea viaje a zona tropical y requiere vacunación y profilaxis",
        },
        "objetivo": "Consulta de medicina del viajero para vacunación y profilaxis antipalúdica pre-viaje",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Itinerario de viaje y destinos específicos",
                "Evaluación de riesgos sanitarios del destino",
                "Revisión de esquema de vacunación actual",
                "Vacunas recomendadas: fiebre amarilla, hepatitis A, tifoidea",
                "Profilaxis antipalúdica según zona",
                "Medidas de protección contra insectos",
                "Seguridad alimentaria e hídrica",
                "Kit de viaje y medicamentos de emergencia",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de medicina del viajero con vacunas internacionales disponibles",
            "restricciones": [
                "Certificado de fiebre amarilla es obligatorio para ingreso a ciertos países",
                "Profilaxis antipalúdica debe iniciarse antes del viaje según el fármaco elegido",
            ],
            "metadata": {
                "especialidad": "medicina_viajero",
                "tipo_consulta": "pre_viaje",
                "vacunas": "internacionales",
            },
        },
        "etiquetas": ["preventivo", "vacunacion", "viajero", "profilaxis", "malaria"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico familiar en chequeo preventivo",
            "Paciente": "Hombre de 50+ años en revisión preventiva anual integral",
        },
        "objetivo": "Chequeo preventivo integral para hombre adulto mayor de 50 años",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Antecedentes familiares y personales actualizados",
                "Revisión de hábitos: tabaco, alcohol, ejercicio, dieta",
                "Exploración física completa",
                "Evaluación cardiovascular: presión, perímetro abdominal",
                "Tamizaje de diabetes y dislipidemia",
                "Tamizaje de cáncer colorrectal",
                "Tamizaje de cáncer de próstata: discusión informada",
                "Evaluación de salud mental y estrés",
                "Actualización de vacunas: influenza, neumococo",
                "Plan de estudios y próxima revisión",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de medicina preventiva con protocolos de tamizaje por grupo etario",
            "restricciones": [
                "Tamizaje de cáncer colorrectal obligatorio a partir de 45-50 años",
                "PSA solo tras discusión informada de riesgos y beneficios con el paciente",
            ],
            "metadata": {
                "especialidad": "medicina_preventiva",
                "tipo_consulta": "chequeo_integral",
                "grupo_etario": "hombre_50_plus",
            },
        },
        "etiquetas": ["preventivo", "chequeo", "tamizaje", "hombre", "integral"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Family medicine physician conducting adult wellness visit",
            "Patient": "Healthy adult seeking annual flu vaccination and preventive health review",
        },
        "objetivo": "Annual wellness visit with seasonal influenza vaccination and preventive care counseling",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Health history update and current concerns",
                "Vital signs and basic physical examination",
                "Age-appropriate cancer screening review",
                "Cardiovascular risk assessment",
                "Immunization review and flu vaccine administration",
                "Lifestyle counseling: diet, exercise, sleep",
                "Mental health check-in",
                "Preventive care plan and next appointment",
            ],
        },
        "parametros_factuales": {
            "contexto": "Family medicine office with on-site vaccination capability and screening tools",
            "restricciones": [
                "Follow USPSTF recommendations for age-appropriate screenings",
                "Flu vaccine contraindicated in severe egg allergy unless evaluated",
            ],
            "metadata": {
                "especialidad": "family_medicine",
                "tipo_consulta": "wellness_visit",
                "vacuna": "influenza_seasonal",
            },
        },
        "etiquetas": ["preventive", "wellness", "flu_vaccine", "screening", "annual"],
    },
    # -------------------------------------------------------------------------
    # 36-40: Post-surgical follow-up
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Cirujano general en consulta de seguimiento postquirúrgico",
            "Paciente": "Persona en primera revisión a 7 días de colecistectomía laparoscópica",
        },
        "objetivo": "Primera revisión postquirúrgica tras colecistectomía laparoscópica electiva",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Evaluación del estado general postquirúrgico",
                "Revisión de heridas y puertos laparoscópicos",
                "Manejo del dolor: medicamentos y evolución",
                "Tolerancia a la vía oral y función intestinal",
                "Actividad física y reincorporación laboral",
                "Signos de alarma postquirúrgicos",
                "Restricciones dietéticas temporales",
                "Retiro de puntos y próxima cita",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de cirugía general con material para curación de heridas",
            "restricciones": [
                "Retiro de puntos entre 7-10 días según evolución de heridas",
                "Reincorporación a actividad laboral sedentaria en 1-2 semanas",
            ],
            "metadata": {
                "especialidad": "cirugia_general",
                "tipo_consulta": "seguimiento_postquirurgico",
                "procedimiento": "colecistectomia_laparoscopica",
                "dias_postcirugia": "7",
            },
        },
        "etiquetas": ["postquirurgico", "colecistectomia", "heridas", "recuperacion"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Traumatólogo en seguimiento de fractura operada",
            "Paciente": "Persona con osteosíntesis de tobillo hace 6 semanas en control radiográfico",
        },
        "objetivo": "Control radiográfico a 6 semanas de osteosíntesis de tobillo y plan de rehabilitación",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Evaluación clínica del tobillo operado",
                "Revisión de radiografía de control",
                "Valoración de consolidación ósea",
                "Evaluación de rango de movimiento actual",
                "Plan de retiro gradual de inmovilización",
                "Referencia a rehabilitación física",
                "Objetivos de rehabilitación y tiempos esperados",
                "Próximo control radiográfico y cita",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio de traumatología con negatoscopio digital para radiografías",
            "restricciones": [
                "Apoyo progresivo según evidencia de consolidación radiográfica",
                "Rehabilitación debe iniciarse al retirar inmovilización",
            ],
            "metadata": {
                "especialidad": "traumatologia",
                "tipo_consulta": "control_postquirurgico",
                "procedimiento": "osteosintesis_tobillo",
                "semanas_postcirugia": "6",
            },
        },
        "etiquetas": ["postquirurgico", "fractura", "tobillo", "radiografia", "rehabilitacion"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Oftalmólogo en seguimiento de cirugía de cataratas",
            "Paciente": "Adulto mayor en revisión al día siguiente de cirugía de catarata",
        },
        "objetivo": "Revisión postquirúrgica al día 1 de facoemulsificación de catarata con lente intraocular",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 6,
            "turnos_max": 14,
            "flujo_esperado": [
                "Evaluación de agudeza visual postquirúrgica",
                "Exploración con lámpara de hendidura",
                "Verificación de posición del lente intraocular",
                "Evaluación de presión intraocular",
                "Revisión de esquema de gotas postoperatorias",
                "Cuidados y restricciones post-cirugía",
            ],
        },
        "parametros_factuales": {
            "contexto": "Consultorio oftalmológico con lámpara de hendidura y tonómetro",
            "restricciones": [
                "Presión intraocular elevada post-cirugía requiere manejo inmediato",
                "No frotar el ojo operado durante mínimo 2 semanas",
            ],
            "metadata": {
                "especialidad": "oftalmologia",
                "tipo_consulta": "postquirurgico_dia1",
                "procedimiento": "facoemulsificacion_catarata",
            },
        },
        "etiquetas": ["postquirurgico", "catarata", "oftalmologia", "lente_intraocular"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Cirujano cardiovascular en seguimiento de bypass coronario",
            "Paciente": "Persona en rehabilitación cardíaca a 4 semanas de cirugía de bypass",
        },
        "objetivo": "Control a 4 semanas de cirugía de bypass coronario con plan de rehabilitación cardíaca",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 22,
            "flujo_esperado": [
                "Estado general y capacidad funcional actual",
                "Evaluación de esternotomía y heridas",
                "Auscultación cardíaca y pulmonar",
                "Control de factores de riesgo cardiovascular",
                "Revisión de medicamentos postquirúrgicos",
                "Progreso en rehabilitación cardíaca",
                "Metas de actividad física gradual",
                "Estado emocional y depresión post-bypass",
                "Restricciones de manejo y actividad laboral",
                "Plan de estudios de control y próxima cita",
            ],
        },
        "parametros_factuales": {
            "contexto": "Clínica de cirugía cardiovascular con programa de rehabilitación cardíaca",
            "restricciones": [
                "No levantar más de 5 kg durante 8-12 semanas post-esternotomía",
                "Tamizaje de depresión recomendado: 25% de pacientes post-bypass la desarrollan",
            ],
            "metadata": {
                "especialidad": "cirugia_cardiovascular",
                "tipo_consulta": "seguimiento_postquirurgico",
                "procedimiento": "bypass_coronario",
                "semanas_postcirugia": "4",
            },
        },
        "etiquetas": ["postquirurgico", "bypass", "cardiovascular", "rehabilitacion", "esternotomia"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Orthopedic surgeon conducting post-op knee replacement check",
            "Patient": "Patient at 2-week follow-up after total knee arthroplasty",
        },
        "objetivo": "Two-week post-operative follow-up after total knee replacement with wound and mobility check",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Overall recovery assessment and pain management",
                "Surgical wound inspection and staple/suture status",
                "Range of motion evaluation",
                "Weight-bearing progress with walker/crutches",
                "Physical therapy compliance and goals",
                "DVT prevention review: anticoagulation and exercises",
                "Warning signs to watch for",
                "Next milestone and follow-up appointment",
            ],
        },
        "parametros_factuales": {
            "contexto": "Orthopedic surgery clinic with physical therapy coordination",
            "restricciones": [
                "Target ROM of 90 degrees flexion by 6 weeks post-op",
                "DVT prophylaxis for minimum 2 weeks post-operatively",
            ],
            "metadata": {
                "especialidad": "orthopedic_surgery",
                "tipo_consulta": "post_operative",
                "procedimiento": "total_knee_arthroplasty",
                "weeks_post_surgery": "2",
            },
        },
        "etiquetas": ["post_surgical", "knee_replacement", "orthopedics", "physical_therapy", "dvt"],
    },
    # -------------------------------------------------------------------------
    # 41-45: Telemedicine / remote consultation
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico general atendiendo por teleconsulta",
            "Paciente": "Persona con infección urinaria recurrente que solicita consulta remota",
        },
        "objetivo": "Teleconsulta por síntomas de infección urinaria no complicada con prescripción remota",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Verificación de identidad y consentimiento para teleconsulta",
                "Interrogatorio de síntomas urinarios",
                "Antecedentes de infecciones previas y tratamientos",
                "Evaluación de factores de complicación",
                "Indicación de examen general de orina si posible",
                "Prescripción empírica si no hay datos de alarma",
                "Explicación de tratamiento y medidas generales",
                "Criterios para acudir presencialmente a urgencias",
            ],
        },
        "parametros_factuales": {
            "contexto": "Plataforma de telemedicina con prescripción electrónica y expediente digital",
            "restricciones": [
                "No prescribir antibióticos por teleconsulta si hay datos de pielonefritis",
                "Derivar a consulta presencial si fiebre mayor a 38°C o dolor lumbar",
            ],
            "metadata": {
                "especialidad": "medicina_general",
                "tipo_consulta": "teleconsulta",
                "modalidad": "videollamada",
                "padecimiento": "infeccion_urinaria",
            },
        },
        "etiquetas": ["telemedicina", "teleconsulta", "urinaria", "prescripcion_remota"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Dermatólogo que atiende por teledermatología",
            "Paciente": "Persona con lesión cutánea que envía fotografías para evaluación remota",
        },
        "objetivo": "Evaluación dermatológica remota mediante fotografías clínicas de lesión cutánea",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Recepción y evaluación de calidad de fotografías",
                "Interrogatorio sobre la lesión: inicio, evolución, síntomas",
                "Antecedentes de exposición solar y dermatológicos",
                "Análisis visual de la lesión en fotografías",
                "Diagnósticos diferenciales posibles",
                "Indicación de tratamiento tópico si aplica",
                "Criterios para biopsia o consulta presencial",
                "Plan de seguimiento fotográfico en 2 semanas",
            ],
        },
        "parametros_factuales": {
            "contexto": "Plataforma de teledermatología con capacidad de almacenamiento de imágenes clínicas",
            "restricciones": [
                "Fotografías deben incluir lesión con regla de referencia y luz natural",
                "Lesiones sospechosas de melanoma requieren evaluación presencial obligatoria",
            ],
            "metadata": {
                "especialidad": "dermatologia",
                "tipo_consulta": "teledermatologia",
                "modalidad": "asincrona_fotografica",
            },
        },
        "etiquetas": ["telemedicina", "dermatologia", "fotografica", "lesion_cutanea"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Psicólogo clínico en sesión de teleterapia",
            "Paciente": "Persona en tratamiento por ansiedad que asiste a sesión semanal por videollamada",
        },
        "objetivo": "Sesión de terapia cognitivo-conductual por videollamada para manejo de ansiedad",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 12,
            "turnos_max": 26,
            "flujo_esperado": [
                "Check-in inicial y estado emocional de la semana",
                "Revisión de tarea terapéutica asignada",
                "Análisis de registro de pensamientos automáticos",
                "Identificación de distorsiones cognitivas",
                "Reestructuración cognitiva guiada",
                "Técnica de relajación o mindfulness",
                "Discusión de situaciones de la semana",
                "Práctica de exposición gradual si aplica",
                "Evaluación de progreso con escala de ansiedad",
                "Asignación de nueva tarea terapéutica",
                "Resumen de la sesión",
                "Próxima cita y ejercicios entre sesiones",
            ],
        },
        "parametros_factuales": {
            "contexto": "Plataforma de teleterapia con herramientas de registro y seguimiento",
            "restricciones": [
                "Verificar privacidad del espacio del paciente al inicio de cada sesión",
                "Tener plan de contacto de emergencia en caso de crisis durante sesión remota",
            ],
            "metadata": {
                "especialidad": "psicologia_clinica",
                "tipo_consulta": "teleterapia",
                "enfoque": "tcc",
                "numero_sesion": "semanal",
            },
        },
        "etiquetas": ["telemedicina", "teleterapia", "tcc", "ansiedad", "videollamada"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico internista en seguimiento remoto de paciente crónico",
            "Paciente": "Persona con hipertensión y diabetes en monitoreo remoto de signos vitales",
        },
        "objetivo": "Consulta de seguimiento remoto con revisión de datos de monitoreo de presión y glucosa",
        "tono": "profesional",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Revisión de datos transmitidos por dispositivos de monitoreo",
                "Análisis de tendencias de presión arterial del mes",
                "Análisis de monitoreo continuo de glucosa",
                "Síntomas reportados en la aplicación de seguimiento",
                "Adherencia a medicamentos registrada",
                "Ajustes terapéuticos basados en datos",
                "Refuerzo de hábitos de vida saludable",
                "Próxima consulta presencial o remota",
            ],
        },
        "parametros_factuales": {
            "contexto": "Programa de monitoreo remoto de pacientes con dispositivos IoT de salud conectados",
            "restricciones": [
                "Alertas automáticas si presión sistólica mayor a 180 mmHg o glucosa mayor a 300 mg/dL",
                "Consulta presencial obligatoria cada 3 meses aunque monitoreo remoto sea adecuado",
            ],
            "metadata": {
                "especialidad": "medicina_interna",
                "tipo_consulta": "monitoreo_remoto",
                "dispositivos": "tensiómetro_bluetooth_glucómetro_continuo",
            },
        },
        "etiquetas": ["telemedicina", "monitoreo_remoto", "iot", "hipertension", "diabetes"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Urgent care physician conducting video visit",
            "Patient": "Parent seeking after-hours consultation for child with fever and rash",
        },
        "objetivo": "After-hours telemedicine evaluation of pediatric fever with rash for triage decision",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 18,
            "flujo_esperado": [
                "Identity verification and consent for telemedicine",
                "Child's symptom history and timeline",
                "Visual assessment of rash via video",
                "Temperature and associated symptoms review",
                "Red flag assessment for meningitis and sepsis",
                "Triage decision: home care vs emergency department",
                "Treatment guidance if appropriate for home care",
                "Clear instructions for when to seek emergency care",
            ],
        },
        "parametros_factuales": {
            "contexto": "After-hours telemedicine service with video capability and ED referral pathway",
            "restricciones": [
                "Non-blanching rash with fever requires immediate ED referral",
                "Cannot perform physical exam remotely; lower threshold for in-person evaluation",
            ],
            "metadata": {
                "especialidad": "urgent_care",
                "tipo_consulta": "telemedicine",
                "modalidad": "video_visit",
                "patient_type": "pediatric",
            },
        },
        "etiquetas": ["telemedicine", "pediatric", "fever", "rash", "triage", "after_hours"],
    },
    # -------------------------------------------------------------------------
    # 46-50: Emergency triage
    # -------------------------------------------------------------------------
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico de urgencias en clasificación triage",
            "Paciente": "Persona que llega a urgencias con dolor torácico agudo",
        },
        "objetivo": "Triage y evaluación inicial de dolor torácico agudo en urgencias",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Toma de signos vitales inmediata",
                "Clasificación triage: nivel de urgencia",
                "Caracterización del dolor torácico",
                "Factores de riesgo cardiovascular rápidos",
                "ECG de 12 derivaciones inmediato",
                "Solicitud de marcadores cardíacos",
                "Decisión: zona de reanimación o área de observación",
                "Inicio de protocolo según hallazgo inicial",
            ],
        },
        "parametros_factuales": {
            "contexto": "Servicio de urgencias con capacidad de ECG inmediato y laboratorio de guardia",
            "restricciones": [
                "Dolor torácico es triage nivel 1-2: evaluación en menos de 10 minutos",
                "ECG debe realizarse dentro de los primeros 10 minutos de llegada",
            ],
            "metadata": {
                "especialidad": "urgencias",
                "tipo_consulta": "triage",
                "prioridad": "alta",
                "sintoma_principal": "dolor_toracico",
            },
        },
        "etiquetas": ["triage", "urgencias", "dolor_toracico", "ecg", "cardiaco"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico de urgencias evaluando politraumatismo",
            "Paciente": "Persona involucrada en accidente vehicular con múltiples lesiones aparentes",
        },
        "objetivo": "Evaluación primaria y estabilización de paciente politraumatizado en urgencias",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "ABCDE primario: vía aérea con protección cervical",
                "Evaluación de respiración y ventilación",
                "Evaluación de circulación y control de hemorragias",
                "Evaluación neurológica rápida: Glasgow",
                "Exposición completa con prevención de hipotermia",
                "Evaluación secundaria cabeza a pies",
                "Estudios de imagen: FAST y radiografías",
                "Interconsultas a especialidades según hallazgos",
                "Plan de manejo definitivo",
                "Comunicación con familiares",
            ],
        },
        "parametros_factuales": {
            "contexto": "Sala de trauma con equipo multidisciplinario y protocolo ATLS",
            "restricciones": [
                "Seguir protocolo ATLS para evaluación primaria sistemática",
                "No retirar inmovilización cervical sin descartar lesión por imagen",
            ],
            "metadata": {
                "especialidad": "urgencias",
                "tipo_consulta": "triage_trauma",
                "protocolo": "atls",
                "prioridad": "critica",
            },
        },
        "etiquetas": ["triage", "urgencias", "trauma", "atls", "politraumatismo"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico de urgencias pediátricas",
            "Paciente": "Padre/madre con lactante que presenta dificultad respiratoria aguda",
        },
        "objetivo": "Evaluación y manejo de dificultad respiratoria aguda en lactante en urgencias pediátricas",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 10,
            "turnos_max": 20,
            "flujo_esperado": [
                "Evaluación rápida del triángulo pediátrico",
                "Toma de signos vitales y oximetría",
                "Evaluación de trabajo respiratorio: tiraje, aleteo, quejido",
                "Historia clínica dirigida con los padres",
                "Auscultación pulmonar y evaluación de hidratación",
                "Clasificación de severidad",
                "Inicio de tratamiento: oxígeno, nebulización",
                "Monitorización continua",
                "Criterios de hospitalización vs alta",
                "Educación a padres sobre signos de alarma",
            ],
        },
        "parametros_factuales": {
            "contexto": "Urgencias pediátricas con equipo de monitoreo y nebulización continua",
            "restricciones": [
                "Saturación de oxígeno menor a 92% requiere suplemento inmediato",
                "Score de severidad de bronquiolitis guía decisión de hospitalización",
            ],
            "metadata": {
                "especialidad": "urgencias_pediatricas",
                "tipo_consulta": "triage",
                "grupo_etario": "lactante",
                "sintoma_principal": "dificultad_respiratoria",
            },
        },
        "etiquetas": ["triage", "urgencias", "pediatrico", "respiratorio", "lactante"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "es",
        "roles": ["Médico", "Paciente"],
        "descripcion_roles": {
            "Médico": "Médico de urgencias evaluando evento cerebrovascular",
            "Paciente": "Persona traída por familiares con sospecha de infarto cerebral",
        },
        "objetivo": "Activación de código ictus y evaluación neurológica de emergencia por sospecha de EVC",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Activación de código ictus y cronómetro",
                "Estabilización inicial de signos vitales",
                "Escala NIHSS rápida",
                "Hora de inicio de síntomas o última vez visto normal",
                "TC de cráneo urgente sin contraste",
                "Glucemia capilar inmediata",
                "Decisión sobre trombólisis según ventana terapéutica",
                "Ingreso a unidad de ictus o UCI",
            ],
        },
        "parametros_factuales": {
            "contexto": "Hospital con protocolo de código ictus y tomógrafo disponible 24/7",
            "restricciones": [
                "Ventana para trombólisis intravenosa: 4.5 horas desde inicio de síntomas",
                "TC debe realizarse en menos de 25 minutos desde llegada",
            ],
            "metadata": {
                "especialidad": "urgencias",
                "tipo_consulta": "codigo_ictus",
                "prioridad": "critica",
                "protocolo": "codigo_ictus",
            },
        },
        "etiquetas": ["triage", "urgencias", "ictus", "evc", "trombólisis", "nihss"],
    },
    {
        "dominio": "medical.consultation",
        "idioma": "en",
        "roles": ["Physician", "Patient"],
        "descripcion_roles": {
            "Physician": "Emergency medicine physician performing triage assessment",
            "Patient": "Individual presenting to ED with acute allergic reaction and facial swelling",
        },
        "objetivo": "Emergency triage and management of acute anaphylaxis with angioedema",
        "tono": "formal",
        "pasos_turnos": {
            "turnos_min": 8,
            "turnos_max": 16,
            "flujo_esperado": [
                "Immediate assessment of airway patency",
                "Vital signs and oxygen saturation",
                "Epinephrine administration decision",
                "Allergen exposure history",
                "Monitoring for biphasic reaction",
                "IV access and fluid resuscitation if needed",
                "Observation period determination",
                "Discharge plan with EpiPen prescription and allergy referral",
            ],
        },
        "parametros_factuales": {
            "contexto": "Emergency department with resuscitation capability and anaphylaxis protocol",
            "restricciones": [
                "Epinephrine IM is first-line treatment for anaphylaxis, do not delay",
                "Minimum 4-6 hours observation for biphasic reaction risk",
            ],
            "metadata": {
                "especialidad": "emergency_medicine",
                "tipo_consulta": "triage",
                "prioridad": "critical",
                "diagnosis": "anaphylaxis",
            },
        },
        "etiquetas": ["triage", "emergency", "anaphylaxis", "epinephrine", "angioedema"],
    },
]
